"""Real-migration execution test for the continuity retry/index hotfix.

Opt-in:

    QIGATEWAY_PG_MIGRATION_TEST=1 python -m pytest \
        tests/test_continuity_retry_pgserver_integration.py -v

生产事故：run 267（continuity，succeeded，0 提取）以旧唯一索引
(assistant_id, source_first_message_id, source_last_message_id)
where mode='execute' and status in ('running','succeeded') 永久占据窗口，
run 268（continuity_retry）初始化撞索引后异常发生在 try 之外、残留 claimed。

测试起点显式重建生产实际索引定义，再应用修复迁移
20260916010000_memory_digest_runs_active_batch_index.sql，验证：
* 旧索引进点确实复现"初始化冲突 + 残留 claimed"；
* 修复后同批重试、二次空结果、随后产生候选的完整路径；
* 并发重复提交保护保留；不同 pipeline 相同区间不互伤；
* 第一批成功、第二批失败后重试，第一批成果保留、游标从断点继续。
"""

import hashlib
import json
import os
import shutil
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MIGRATIONS_DIR = ROOT / "supabase" / "migrations"
FIX_MIGRATION = "20260916010000_memory_digest_runs_active_batch_index.sql"
PG_TRGM_LINE = "create extension if not exists pg_trgm with schema extensions;"
PG_TRGM_FILE = "20260804020000_auto_digest_memory_requests.sql"

OLD_INDEX_SQL = """
create unique index memory_digest_runs_active_batch_uidx
    on public.memory_digest_runs
    (assistant_id, source_first_message_id, source_last_message_id)
    where mode = 'execute'
      and status in ('running', 'succeeded');
"""

try:
    import pgserver
    import psycopg
    _STACK_AVAILABLE = True
except ImportError:  # pragma: no cover - optional heavyweight stack
    _STACK_AVAILABLE = False

BASELINE_SQL = """
create role anon nologin;
create role authenticated nologin;
create role service_role nologin bypassrls;

create schema if not exists extensions;
create extension if not exists vector with schema extensions;

create function extensions.similarity(p_left text, p_right text)
returns double precision
language sql
immutable
parallel safe
as $stub$
    select case when p_left = p_right then 1.0 else 0.0 end
$stub$;

grant usage on schema public, extensions to anon, authenticated, service_role;

create table public.chat_messages (
    id bigint generated by default as identity primary key,
    assistant_id text not null,
    conversation_id text,
    role text,
    content text,
    created_at timestamptz not null default now()
);

create table public.memories (
    id integer generated by default as identity primary key,
    content text not null,
    title text,
    tags text[],
    heat double precision not null default 50,
    importance integer,
    layer text,
    embedding extensions.vector,
    source text,
    verified text not null default 'verified',
    is_active boolean not null default true,
    emotion_weight double precision,
    recall_count integer not null default 0,
    digest_run_id bigint,
    source_first_message_id bigint,
    source_last_message_id bigint,
    confidence double precision,
    content_hash text unique,
    created_at timestamptz not null default now(),
    last_recalled_at timestamptz
);

create table public.memory_digest_runs (
    id bigint generated by default as identity primary key,
    assistant_id text not null,
    mode text not null default 'execute',
    status text not null default 'running',
    trigger text,
    source_first_message_id bigint,
    source_last_message_id bigint,
    started_at timestamptz not null default now(),
    completed_at timestamptz,
    message_count integer,
    extracted_count integer,
    inserted_count integer,
    preview_memories jsonb,
    error_code text,
    error_message text
);

create table public.memory_digest_cursors (
    id bigint generated by default as identity primary key,
    assistant_id text not null unique,
    last_processed_message_id bigint not null default 0,
    last_success_at timestamptz,
    updated_at timestamptz not null default now()
);

grant select, update on public.memories to service_role;
"""

ASSISTANT = "a-continuity"

SEED_SQL = """
insert into public.chat_messages (id, assistant_id, conversation_id, role, content, created_at) values
    (2461, 'a-continuity', 'c-acc', 'user', '我们计划下周把验收流程走一遍。', '2026-09-13 09:00+08'),
    (2462, 'a-continuity', 'c-acc', 'assistant', '好，验收流程我记着，下周一起走。', '2026-09-13 09:01+08'),
    (2463, 'a-continuity', 'c-acc', 'user', '第二阶段：把部署脚本也梳理一遍。', '2026-09-13 10:00+08'),
    (2464, 'a-continuity', 'c-acc', 'assistant', '部署脚本梳理也排上了。', '2026-09-13 10:01+08'),
    (2465, 'a-continuity', 'c-acc', 'user', '备用窗口内容一。', '2026-09-13 11:00+08'),
    (2466, 'a-continuity', 'c-acc', 'assistant', '备用窗口内容二。', '2026-09-13 11:01+08');

insert into public.memory_continuity_cursors (assistant_id, last_processed_message_id)
values ('a-continuity', 2460);
"""


def _sha256(text: str) -> str:
    return hashlib.sha256(text.casefold().encode("utf-8")).hexdigest()


def _candidate(content: str, evidence):
    return {
        "content": content,
        "continuity_type": "thread",
        "continuity_schema_version": 1,
        "thread_state": "open",
        "continuity_data": {
            "open_question": "验收流程是否推进", "current_state": "进行中",
            "closure_criteria": ["完成"],
        },
        "subject": "project",
        "source_type": "natural_chat",
        "importance": 6,
        "continuity_value": 8,
        "confidence": 0.9,
        "evidence_message_ids": list(evidence),
        "evidence_start_time": "2026-09-13 09:00+08:00",
        "evidence_end_time": "2026-09-13 09:01+08:00",
        "source_time": "2026-09-13 09:00+08:00",
        "memory_time": None,
        "time_precision": "unknown",
        "title": content[:20],
        "participants": ["yezi", "qi"],
        "reason": "验收样例候选。",
        "retention_class": "normal",
        "content_hash": _sha256(content),
        "embedding": "[0.1,0.2,0.3]",
    }


def _ensure_pg_timezone_data():
    """pgserver 的 PostgreSQL 没有附带 IANA 时区文件。"""
    pg_install = Path(pgserver.__file__).parent / "pginstall"
    tzdir = pg_install / "share" / "postgresql" / "timezone"
    if (tzdir / "Asia" / "Shanghai").exists():
        return
    try:
        import tzdata
    except ImportError:  # pragma: no cover - depends on environment
        raise unittest.SkipTest("Python tzdata package unavailable")
    src = Path(tzdata.__file__).parent / "zoneinfo"
    tzdir.mkdir(parents=True, exist_ok=True)
    shutil.copytree(src, tzdir, dirs_exist_ok=True)


class ContinuityRetryIndexTests(unittest.TestCase):
    """Executes the continuity retry flow on a real, disposable database."""

    @classmethod
    def setUpClass(cls):
        if not _STACK_AVAILABLE:
            raise unittest.SkipTest("pgserver + psycopg are not installed")
        if os.environ.get("QIGATEWAY_PG_MIGRATION_TEST") != "1":
            raise unittest.SkipTest(
                "set QIGATEWAY_PG_MIGRATION_TEST=1 to run the real "
                "PostgreSQL migration execution test"
            )
        cls.pgdata = Path(tempfile.mkdtemp(prefix="qigate-continuity-"))
        cls.server = None
        cls.conn = None
        try:
            _ensure_pg_timezone_data()
            cls.server = pgserver.get_server(cls.pgdata, cleanup_mode="stop")
            cls.conn = psycopg.connect(cls.server.get_uri(), autocommit=True)
            cls.conn.execute(BASELINE_SQL)
            for path in sorted(MIGRATIONS_DIR.glob("*.sql")):
                if path.name == FIX_MIGRATION:
                    continue  # 修复迁移在测试内部分两阶段应用
                sql = path.read_text(encoding="utf-8")
                if path.name == PG_TRGM_FILE:
                    sql = sql.replace(PG_TRGM_LINE, "-- pg_trgm stubbed (pgserver)")
                try:
                    cls.conn.execute(sql)
                except Exception as exc:
                    raise RuntimeError(f"migration replay failed: {path.name}") from exc
            # 生产实际索引定义（仓库迁移不含它，生产为手工创建）。
            cls.conn.execute(OLD_INDEX_SQL)
            cls.conn.execute(SEED_SQL)
        except Exception:
            cls.tearDownClass()
            raise

    @classmethod
    def tearDownClass(cls):
        conn = getattr(cls, "conn", None)
        if conn is not None:
            conn.close()
            cls.conn = None
        server = getattr(cls, "server", None)
        if server is not None:
            server.cleanup()
            cls.server = None
        pgdata = getattr(cls, "pgdata", None)
        if pgdata is not None and pgdata.exists():
            shutil.rmtree(pgdata, ignore_errors=True)

    # -- helpers ----------------------------------------------------------

    def _claim(self, trigger="continuity_retry"):
        with self.conn.cursor() as cur:
            cur.execute(
                "select public.claim_digest_slot(%s, %s, %s)",
                (ASSISTANT, trigger, "execute"),
            )
            return cur.fetchall()[0][0]

    def _init(self, run_id, first, last, *, pipeline="continuity"):
        """复刻 _set_running_run 的初始化 UPDATE（status running + 窗口）。"""
        self.conn.execute(
            "update public.memory_digest_runs set status = 'running', "
            "pipeline = %s, source_first_message_id = %s, "
            "source_last_message_id = %s, message_count = %s "
            "where id = %s",
            (pipeline, first, last, last - first + 1, run_id),
        )

    def _mark_failed(self, run_id):
        self.conn.execute(
            "update public.memory_digest_runs set status = 'failed', "
            "error_code = 'test_cleanup', completed_at = now(), "
            "heartbeat_at = null where id = %s",
            (run_id,),
        )

    def _pause_empty(self, run_id):
        with self.conn.cursor() as cur:
            cur.execute("select public.pause_memory_continuity_empty(%s)", (run_id,))
            return cur.fetchall()[0][0]

    def _commit(self, run_id, candidates):
        with self.conn.cursor() as cur:
            cur.execute(
                "select public.commit_memory_continuity_run(%s, %s::jsonb)",
                (run_id, json.dumps(candidates, ensure_ascii=False)),
            )
            return cur.fetchall()[0][0]

    def _run_status(self, run_id):
        with self.conn.cursor() as cur:
            cur.execute(
                "select status from public.memory_digest_runs where id = %s",
                (run_id,),
            )
            rows = cur.fetchall()
            return rows[0][0] if rows else None

    def _cursor_row(self):
        with self.conn.cursor() as cur:
            cur.execute(
                "select last_processed_message_id, status "
                "from public.memory_continuity_cursors where assistant_id = %s",
                (ASSISTANT,),
            )
            return cur.fetchall()[0]

    def _claim_error(self, trigger="continuity_retry"):
        with self.conn.cursor() as cur:
            cur.execute(
                "select public.claim_digest_slot(%s, %s, %s)",
                (ASSISTANT, trigger, "execute"),
            )
            return cur.fetchall()[0][0]

    # -- phase 1：旧索引起点复现生产故障 ----------------------------------

    def test_phase1_old_index_reproduces_stuck_claimed(self):
        # 生产前提：run 267（同窗口 succeeded）已占据旧索引的 running/succeeded。
        self.conn.execute(
            "insert into public.memory_digest_runs "
            "(assistant_id, pipeline, trigger, mode, status, "
            "source_first_message_id, source_last_message_id, message_count, "
            "claimed_at, started_at, completed_at) values "
            "(%s, 'continuity', 'continuity_manual', 'execute', 'succeeded', "
            "2461, 2464, 4, now(), now(), now())",
            (ASSISTANT,),
        )
        claim = self._claim("continuity_manual")
        self.assertEqual(claim["status"], "claimed")
        run_id = int(claim["run_id"])
        with self.assertRaises(psycopg.errors.UniqueViolation) as raised:
            self._init(run_id, 2461, 2464)
        self.assertIn("memory_digest_runs_active_batch_uidx", str(raised.exception))
        # 异常发生在初始化：run 残留 claimed（生产 run 268 的形态）。
        self.assertEqual(self._run_status(run_id), "claimed")
        # 恢复动作（与生产恢复方案一致）：显式记失败，结束占用。
        self._mark_failed(run_id)
        self.assertEqual(self._run_status(run_id), "failed")

    # -- phase 2：修复迁移后的完整路径 ------------------------------------

    def test_phase2_fix_enables_retry_and_full_path(self):
        # 应用修复迁移（旧索引被替换为 pipeline 维度、仅活跃状态的索引）。
        self.conn.execute(
            (MIGRATIONS_DIR / FIX_MIGRATION).read_text(encoding="utf-8")
        )

        # 1) 同批重试不再撞索引：初始化成功后空结果暂停。
        claim = self._claim("continuity_manual")
        run_id = int(claim["run_id"])
        self._init(run_id, 2461, 2462)
        cursor = self._pause_empty(run_id)
        self.assertEqual(cursor["status"], "paused_empty")
        self.assertEqual(self._run_status(run_id), "succeeded")

        # 2) 二次空结果：同样成功暂停。
        claim = self._claim("continuity_retry")
        run_id = int(claim["run_id"])
        self._init(run_id, 2461, 2462)
        self._pause_empty(run_id)
        last, status = self._cursor_row()
        self.assertEqual((last, status), (2460, "paused_empty"))

        # 3) 随后产生候选：提交成功，游标推进、暂停解除。
        claim = self._claim("continuity_retry")
        run_id = int(claim["run_id"])
        self._init(run_id, 2461, 2462)
        inserted = self._commit(run_id, [
            _candidate("验收样例：下周一起走一遍验收流程的完整计划。", [2461, 2462]),
        ])
        self.assertEqual(inserted, 1)
        # 候选进入审核队列（连续感候选的正常去向：pending 等叶子审核）。
        self.assertEqual(self._query_count(
            "select count(*) from public.memory_requests where assistant_id = %s "
            "and content_hash = %s and status = 'pending' and source = 'daily_digest'",
            (ASSISTANT, _sha256("验收样例：下周一起走一遍验收流程的完整计划。")),
        ), 1)
        last, status = self._cursor_row()
        self.assertEqual((last, status), (2462, "ready"))

        # 4) 第一批成功、第二批失败后重试：成果保留、从断点继续。
        claim = self._claim("continuity_manual")
        run_id = int(claim["run_id"])
        self._init(run_id, 2463, 2464)
        self._mark_failed(run_id)  # 模拟第二批运行中失败
        claim = self._claim("continuity_manual")
        run_id = int(claim["run_id"])
        self._init(run_id, 2463, 2464)
        inserted = self._commit(run_id, [
            _candidate("验收样例：部署脚本梳理也一起排上了。", [2463, 2464]),
        ])
        self.assertEqual(inserted, 1)
        last, _ = self._cursor_row()
        self.assertEqual(last, 2464)
        # 第一批成果保留：候选申请仍在，未被后续失败波及。
        self.assertEqual(self._query_count(
            "select count(*) from public.memory_requests "
            "where content_hash = %s and status = 'pending'",
            (_sha256("验收样例：下周一起走一遍验收流程的完整计划。"),),
        ), 1)

        # 5) 并发重复提交保护保留：同 pipeline 同窗口两个 running 冲突。
        claim = self._claim("continuity_manual")
        run_id = int(claim["run_id"])
        self._init(run_id, 2465, 2466)
        self.conn.execute(
            "insert into public.memory_digest_runs "
            "(assistant_id, trigger, mode, status, pipeline, claimed_at, "
            "heartbeat_at, started_at) values "
            "(%s, 'continuity_retry', 'execute', 'claimed', 'continuity', "
            "now(), now(), now())",
            (ASSISTANT,),
        )
        duplicate_id = self._query_count(
            "select id from public.memory_digest_runs where assistant_id = %s "
            "and status = 'claimed' order by id desc limit 1",
            (ASSISTANT,),
        )
        with self.assertRaises(psycopg.errors.UniqueViolation):
            self._init(duplicate_id, 2465, 2466)
        self._mark_failed(run_id)
        self._mark_failed(duplicate_id)

        # 6) 不同 pipeline 相同区间不互伤。
        dbg_rows = self._query_count(
            "select coalesce(string_agg(id || ':' || status || ':' || pipeline, ' | '), 'none') "
            "from public.memory_digest_runs where assistant_id = %s "
            "and status in ('claimed', 'running')",
            (ASSISTANT,),
        )
        print("DEBUG step6 active rows:", dbg_rows, "| claim:", claim)
        print("DEBUG index:", self._query_count(
            "select indexdef from pg_indexes "
            "where indexname = 'memory_digest_runs_active_batch_uidx'"))
        print("DEBUG all indexes:", self._query_count(
            "select string_agg(indexdef, ' || ') from pg_indexes "
            "where tablename = 'memory_digest_runs'"))
        print("DEBUG window rows:", self._query_count(
            "select coalesce(string_agg(id || ':' || status, ' | '), 'none') "
            "from public.memory_digest_runs where assistant_id = %s "
            "and source_first_message_id = 2461 and source_last_message_id = 2462",
            (ASSISTANT,)))
        claim = self._claim("continuity_manual")
        continuity_run = int(claim["run_id"])
        self._init(continuity_run, 2461, 2462)
        self.conn.execute(
            "insert into public.memory_digest_runs "
            "(assistant_id, trigger, mode, status, pipeline, claimed_at, "
            "heartbeat_at, started_at) values "
            "(%s, 'manual_execute', 'execute', 'claimed', 'legacy', "
            "now(), now(), now())",
            (ASSISTANT,),
        )
        digest_run = self._query_count(
            "select id from public.memory_digest_runs where assistant_id = %s "
            "and pipeline = 'legacy' and status = 'claimed' "
            "order by id desc limit 1",
            (ASSISTANT,),
        )
        self._init(digest_run, 2461, 2462, pipeline="legacy")  # 同区间、不同 pipeline：不冲突
        self._mark_failed(continuity_run)
        self._mark_failed(digest_run)

    # -- phase 3：已完成批次的陈旧请求不得重复处理/重新暂停 ----------------

    def test_phase3_stale_batch_after_completion_cannot_reprocess(self):
        # A 完成 2465–2466：候选提交、游标推进到 2466 ready。
        claim = self._claim("continuity_manual")
        run_a = int(claim["run_id"])
        self._init(run_a, 2465, 2466)
        content_a = "验收样例：批次 A 的候选内容，先完成处理。"
        self.assertEqual(self._commit(run_a, [_candidate(content_a, [2465])]), 1)
        self.assertEqual(self._cursor_row(), (2466, "ready"))

        # B 陈旧请求持有同一旧批次（A 完成后才领取）：succeeded 不再挡
        # 领取与初始化，但写入与暂停受陈旧守卫约束。
        claim = self._claim("continuity_manual")
        run_b = int(claim["run_id"])
        self._init(run_b, 2465, 2466)

        # B 带不同候选提交 → 陈旧守卫拒绝：无新候选写入、A 成果保留。
        content_b = "验收样例：批次 B 陈旧请求的候选内容，不得写入。"
        with self.assertRaises(psycopg.errors.RaiseException) as raised:
            self._commit(run_b, [_candidate(content_b, [2466])])
        self.assertIn(
            "memory_continuity_batch_already_processed", str(raised.exception),
        )
        self.assertEqual(self._query_count(
            "select count(*) from public.memory_requests where content_hash = %s",
            (_sha256(content_b),),
        ), 0)
        self.assertEqual(self._query_count(
            "select count(*) from public.memory_requests where content_hash = %s",
            (_sha256(content_a),),
        ), 1)
        self._mark_failed(run_b)

        # B 空结果暂停 → already_processed：游标不回退、不再 paused。
        claim = self._claim("continuity_manual")
        run_d = int(claim["run_id"])
        self._init(run_d, 2465, 2466)
        pause_result = self._pause_empty(run_d)
        self.assertEqual(pause_result["status"], "already_processed")
        self.assertEqual(pause_result["last_processed_message_id"], 2466)
        self.assertEqual(self._cursor_row(), (2466, "ready"))
        self.assertEqual(self._run_status(run_d), "succeeded")
        self.assertEqual(self._query_count(
            "select status from public.memory_continuity_cursors "
            "where assistant_id = %s",
            (ASSISTANT,),
        ), "ready")

    def _query_count(self, sql, params=None):
        with self.conn.cursor() as cur:
            cur.execute(sql, params)
            return cur.fetchall()[0][0]


if __name__ == "__main__":
    unittest.main()
