"""Phase 1R 数据库不变量真 PostgreSQL 验证（MEDIUM #10 修复要求）。

Opt-in（启动一次性 pgserver 实例，成本较高）：

    QIGATEWAY_PG_PLANNING_TEST=1 python -m pytest \
        tests/test_planning_phase1r_pgserver_integration.py -v

按顺序重放全部迁移（两个 20260924 规划迁移与 20260927 窗口模型迁移为
被测对象），随后在真实 PostgreSQL 上验证数据库层兜底的不变量：

- 关闭 / 超时实例不得改回开放生命周期（触发器拒绝）；
- handled_at 写入后不可改写（触发器拒绝）；
- 轮次身份不可变（触发器拒绝）；
- display_cycle_date >= schedule_date 与 closed_at/handled_at 形状（CHECK）；
- 轮次唯一性（部分唯一索引）；
- 中空两阶段成对写入（约束触发器）；
- 可安排时段窗口列形状（批次 2）：§18 四种组合均可落库，模板双端不等 /
  实例双端有序 CHECK 生效（施工计划 §3.6：本地语法解析不算数）。

被测迁移文件逐字节从磁盘执行；测试绝不触碰任何生产数据库。
"""

import os
import re
import shutil
import tempfile
import threading
import time
import unittest
from datetime import time as _time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MIGRATIONS_DIR = ROOT / "supabase" / "migrations"
# 最终并发收口（F1/F2）双连接验证共用的处理时刻
REPRO_NOW = "2026-10-20T12:00:00+08:00"
UNDER_TEST = (
    "20260924010000_planning_phase1a_domain_identity.sql",
    "20260924020000_planning_phase1b_refresh.sql",
    "20260927010000_planning_window_model.sql",
)
WINDOW_MIGRATION = MIGRATIONS_DIR / "20260927010000_planning_window_model.sql"


def _split_top_level_statements(sql):
    """把迁移 SQL 拆成顶层语句序列（仅服务窗口迁移重放测试的最小实现）。

    逐字符扫描：跳过 ``--`` 行注释；单引号字符串（含 ``''`` 转义）与
    ``$tag$`` 美元引用块内部的分号不拆分——``DO $$ ... $$`` 等复合块保持
    完整；语句按文件真实顺序返回，显式 ``begin`` / ``commit`` 原样保留。
    逐条发送时原子性只能来自迁移文件自身的事务边界，而不是 Simple Query
    对整串语句提供的隐式事务。
    """
    statements = []
    buf = []
    i = 0
    n = len(sql)
    in_line_comment = False
    in_single_quote = False
    dollar_tag = None
    while i < n:
        ch = sql[i]
        if in_line_comment:
            if ch == "\n":
                in_line_comment = False
                buf.append(" ")
            i += 1
            continue
        if in_single_quote:
            buf.append(ch)
            if ch == "'":
                if sql.startswith("''", i):
                    buf.append("'")
                    i += 2
                    continue
                in_single_quote = False
            i += 1
            continue
        if dollar_tag is not None:
            if sql.startswith(dollar_tag, i):
                buf.append(dollar_tag)
                i += len(dollar_tag)
                dollar_tag = None
            else:
                buf.append(ch)
                i += 1
            continue
        if sql.startswith("--", i):
            in_line_comment = True
            i += 2
            continue
        if ch == "'":
            in_single_quote = True
            buf.append(ch)
            i += 1
            continue
        match = re.match(r"\$(\w*)\$", sql[i:])
        if match:
            dollar_tag = match.group(0)
            buf.append(dollar_tag)
            i += len(dollar_tag)
            continue
        if ch == ";":
            statement = "".join(buf).strip()
            if statement:
                statements.append(statement)
            buf = []
            i += 1
            continue
        buf.append(ch)
        i += 1
    tail = "".join(buf).strip()
    if tail:
        statements.append(tail)
    return statements
PG_TRGM_LINE = "create extension if not exists pg_trgm with schema extensions;"
PG_TRGM_FILE = "20260804020000_auto_digest_memory_requests.sql"

try:
    import pgserver
    import psycopg
    _STACK_AVAILABLE = True
except ImportError:  # pragma: no cover - optional heavyweight stack
    _STACK_AVAILABLE = False

# 复用全链路迁移测试的同一基线骨架：本仓迁移链不含最初建
# memories / chat_messages 的迁移，重放前需要这些表存在。
# 与 test_migration_pgserver_integration.py 的 BASELINE_SQL 保持一致。
BASELINE_SQL = """
-- Roles referenced by every migration's grants/revokes. service_role 在生产
-- Supabase 里带 bypassrls 属性，RLS 策略对它不生效。
create role anon nologin;
create role authenticated nologin;
create role service_role nologin bypassrls;

create schema if not exists extensions;
create extension if not exists vector with schema extensions;

-- pgserver does not ship pg_trgm; deterministic stand-in so that
-- public.memory_dedupe_text_similarity can be created and executed.
create function extensions.similarity(p_left text, p_right text)
returns double precision
language sql
immutable
parallel safe
as $stub$
    select case when p_left = p_right then 1.0 else 0.0 end
$stub$;

grant usage on schema public, extensions to anon, authenticated, service_role;

-- Pre-existing production tables that the migration history expects to find.
create table public.chat_messages (
    id bigint generated by default as identity primary key,
    assistant_id text not null,
    conversation_id text,
    content text,
    created_at timestamptz not null default now()
);

create table public.memories (
    id integer generated by default as identity primary key,
    content text not null,
    title text,
    tags text[],
    heat double precision not null default 50,
    importance integer,
    layer text,
    embedding extensions.vector,
    source text,
    verified text not null default 'verified',
    is_active boolean not null default true,
    emotion_weight double precision,
    recall_count integer not null default 0,
    digest_run_id bigint,
    source_first_message_id bigint,
    source_last_message_id bigint,
    confidence double precision,
    -- 生产 memories 表先于本仓库的迁移历史存在；历史函数（如
    -- review_memory_request_v2 的 on conflict (content_hash)）依赖其唯一约束。
    content_hash text unique,
    created_at timestamptz not null default now(),
    last_recalled_at timestamptz
);

create table public.memory_digest_runs (
    id bigint generated by default as identity primary key,
    assistant_id text not null,
    mode text not null default 'execute',
    status text not null default 'running',
    trigger text,
    source_first_message_id bigint,
    source_last_message_id bigint,
    started_at timestamptz not null default now(),
    completed_at timestamptz,
    message_count integer,
    extracted_count integer,
    inserted_count integer,
    preview_memories jsonb,
    error_code text,
    error_message text
);

create table public.memory_digest_cursors (
    id bigint generated by default as identity primary key,
    assistant_id text not null unique,
    last_processed_message_id bigint not null default 0,
    last_success_at timestamptz,
    updated_at timestamptz not null default now()
);

-- 生产 Supabase 库由 default privileges 把表权限授予 service_role
-- （本仓库的历史迁移从不直接对 memories 授权）。临时库手工补齐同等权限，
-- 否则非 security definer 的 match_memories / search_memories_by_keywords /
-- run_memory_heat_decay 以 service_role 调用时会因表权限不足而失败。
grant select, update on public.memories to service_role;
"""


def _ensure_pg_timezone_data():
    """pgserver 不附带 IANA 时区文件；从 Python tzdata 复制（同源 tzfile）。"""
    pg_install = Path(pgserver.__file__).parent / "pginstall"
    tzdir = pg_install / "share" / "postgresql" / "timezone"
    if (tzdir / "Asia" / "Shanghai").exists():
        return
    try:
        import tzdata
    except ImportError:  # pragma: no cover
        raise unittest.SkipTest("Python tzdata package unavailable")
    src = Path(tzdata.__file__).parent / "zoneinfo"
    tzdir.mkdir(parents=True, exist_ok=True)
    shutil.copytree(src, tzdir, dirs_exist_ok=True)


TASK_SQL = """
insert into public.planning_task (
    content, task_type, time_mode, estimated_minutes, is_active,
    refresh_mode, refresh_enabled, created_at, updated_at
) values (
    '背单词', 'daily', 'duration', 30, true,
    'daily', true, '2026-09-23T07:00:00+08:00', '2026-09-23T07:00:00+08:00'
) returning id;
"""

OCC_SQL = """
insert into public.planning_occurrence (
    task_id, for_date, round_key, schedule_date, display_cycle_date,
    display_reason, status, sort_order, is_fixed, estimated_time_source,
    fixed_source, schedule_managed, is_limited, source,
    content_snapshot, display_content, time_mode_snapshot, deadline_at,
    window_start_at, window_end_at,
    created_at, updated_at
) values (
    %(task_id)s, '2026-09-24', 'cycle:2026-09-24', '2026-09-24', '2026-09-24',
    'initial', 'pending', 10, false, 'unassigned',
    null, true, false, 'schedule',
    '背单词', '背单词', 'duration', null,
    null, null,
    '2026-09-24T06:00:00+08:00', '2026-09-24T06:00:00+08:00'
) returning id;
"""


class PlanningInvariantsOnPostgresTests(unittest.TestCase):
    """在真实 PostgreSQL 上验证规划数据库层兜底不变量。"""

    @classmethod
    def setUpClass(cls):
        if not _STACK_AVAILABLE:
            raise unittest.SkipTest("pgserver + psycopg are not installed")
        if os.environ.get("QIGATEWAY_PG_PLANNING_TEST") != "1":
            raise unittest.SkipTest(
                "set QIGATEWAY_PG_PLANNING_TEST=1 to run the real PostgreSQL "
                "planning invariant test"
            )
        cls.pgdata = Path(tempfile.mkdtemp(prefix="qigate-planning-pg-"))
        cls.server = None
        cls.conn = None
        try:
            _ensure_pg_timezone_data()
            cls.server = pgserver.get_server(cls.pgdata, cleanup_mode="stop")
            cls.conn = psycopg.connect(cls.server.get_uri(), autocommit=True)
            cls.conn.execute(BASELINE_SQL)
            for path in sorted(MIGRATIONS_DIR.glob("*.sql")):
                sql = path.read_text(encoding="utf-8")
                if path.name == PG_TRGM_FILE:
                    assert PG_TRGM_LINE in sql, "pg_trgm line drifted"
                    sql = sql.replace(PG_TRGM_LINE, "-- pg_trgm stubbed (pgserver)")
                cls.conn.execute(sql)
            cls.task_id = cls._query(TASK_SQL)[0][0]
            cls.occ_id = cls._query(OCC_SQL, {"task_id": cls.task_id})[0][0]
        except Exception:
            cls.tearDownClass()
            raise

    @classmethod
    def tearDownClass(cls):
        conn = getattr(cls, "conn", None)
        if conn is not None:
            conn.close()
            cls.conn = None
        server = getattr(cls, "server", None)
        if server is not None:
            server.cleanup()
            cls.server = None
        pgdata = getattr(cls, "pgdata", None)
        if pgdata is not None and pgdata.exists():
            shutil.rmtree(pgdata, ignore_errors=True)

    # -- helpers ----------------------------------------------------------

    @classmethod
    def _query(cls, sql, params=None):
        with cls.conn.cursor() as cur:
            cur.execute(sql, params)
            if cur.description:
                return cur.fetchall()
            return []

    def _task_id(self):
        row = self._query("select id from public.planning_task order by id limit 1")
        return row[0][0]

    def _fresh_occurrence(self, **overrides):
        """插入一个合法的新版 pending 实例，返回其 id。

        窗口列（批次 2）默认 NULL=无窗口；可用 window_start_at /
        window_end_at 覆盖（aware ISO 字符串或 datetime 均可）。
        """
        schedule_date = overrides.pop("schedule_date", "2026-09-25")
        round_key = overrides.pop("round_key", f"cycle:{schedule_date}")
        params = {
            "task_id": overrides.pop("task_id", self._task_id()),
            "round_key": round_key,
            "schedule_date": schedule_date,
            "display_cycle_date": overrides.pop("display_cycle_date", schedule_date),
            "display_reason": overrides.pop("display_reason", "initial"),
            "status": overrides.pop("status", "pending"),
            "closed_at": overrides.pop("closed_at", None),
            "handled_at": overrides.pop("handled_at", None),
            "source": "early" if str(round_key).startswith("early:") else "schedule",
            "early_period_date": overrides.pop(
                "early_period_date",
                str(schedule_date) if str(round_key).startswith("early:") else None),
            "window_start_at": overrides.pop("window_start_at", None),
            "window_end_at": overrides.pop("window_end_at", None),
        }
        params.update(overrides)
        sql = """
        insert into public.planning_occurrence (
            task_id, for_date, round_key, schedule_date, display_cycle_date,
            display_reason, status, closed_at, handled_at, sort_order, is_fixed,
            estimated_time_source, fixed_source, schedule_managed, is_limited,
            source, early_period_date,
            content_snapshot, display_content, time_mode_snapshot, deadline_at,
            window_start_at, window_end_at,
            created_at, updated_at
        ) values (
            %(task_id)s, %(schedule_date)s, %(round_key)s, %(schedule_date)s,
            %(display_cycle_date)s, %(display_reason)s, %(status)s, %(closed_at)s,
            %(handled_at)s, 20, false, 'unassigned', null, true, false,
            %(source)s, %(early_period_date)s,
            '快照', '快照', 'duration', null,
            %(window_start_at)s, %(window_end_at)s,
            '2026-09-24T06:00:00+08:00', '2026-09-24T06:00:00+08:00'
        ) returning id;
        """
        return self._query(sql, params)[0][0]

    def _assert_raises(self, sql, params, fragment):
        with self.assertRaises(psycopg.errors.RaiseException) as caught:
            self._query(sql, params)
        self.assertIn(fragment, str(caught.exception))

    # -- identity & shape --------------------------------------------------

    def test_display_cycle_can_never_precede_schedule_date(self):
        with self.assertRaises(psycopg.errors.CheckViolation):
            self._fresh_occurrence(
                round_key="cycle:2026-09-26",
                schedule_date="2026-09-26",
                display_cycle_date="2026-09-25",
                display_reason="carryover",
            )

    def test_closed_at_shape_follows_status(self):
        with self.assertRaises(psycopg.errors.CheckViolation):
            self._fresh_occurrence(status="completed", closed_at=None, handled_at="2026-09-25T08:00:00+08:00")

    def test_round_uniqueness_is_enforced_by_database(self):
        self._fresh_occurrence(round_key="cycle:2026-09-27", schedule_date="2026-09-27")
        with self.assertRaises(psycopg.errors.UniqueViolation):
            self._fresh_occurrence(round_key="cycle:2026-09-27", schedule_date="2026-09-27")

    # -- trigger guards ----------------------------------------------------

    def test_closed_occurrence_cannot_reenter_open_lifecycle(self):
        occ = self._fresh_occurrence(
            round_key="cycle:2026-09-28", schedule_date="2026-09-28",
            status="completed", closed_at="2026-09-28T09:00:00+08:00",
            handled_at="2026-09-28T09:00:00+08:00",
        )
        for target in ("pending", "in_progress", "deferred", "partial"):
            with self.subTest(target=target):
                # 现实复活写法：状态与 closed_at 同时改写 → 触发器兜底拒绝
                self._assert_raises(
                    "update public.planning_occurrence set status = %(target)s, "
                    "closed_at = null, handled_at = null where id = %(id)s",
                    {"target": target, "id": occ},
                    "closed occurrences cannot re-enter the open lifecycle",
                )
        # 惰性写法（只改状态）→ closed_at 形状 CHECK 同样拒绝
        with self.assertRaises(psycopg.errors.CheckViolation):
            self._query(
                "update public.planning_occurrence set status = 'pending' where id = %(id)s",
                {"id": occ},
            )

    def test_timeout_occurrence_cannot_reenter_open_lifecycle(self):
        occ = self._fresh_occurrence(
            round_key="cycle:2026-09-29", schedule_date="2026-09-29",
            status="timeout", closed_at="2026-09-29T12:00:00+08:00",
        )
        self._assert_raises(
            "update public.planning_occurrence set status = 'pending', closed_at = null "
            "where id = %(id)s",
            {"id": occ},
            "closed occurrences cannot re-enter the open lifecycle",
        )

    def test_handled_at_is_immutable_once_written(self):
        occ = self._fresh_occurrence(
            round_key="cycle:2026-09-30", schedule_date="2026-09-30",
            status="completed", closed_at="2026-09-30T09:00:00+08:00",
            handled_at="2026-09-30T09:00:00+08:00",
        )
        # 关闭态之间更正状态标签允许，但 handled_at 不得改写
        self._query(
            "update public.planning_occurrence set status = 'discarded_this' where id = %(id)s",
            {"id": occ},
        )
        self._assert_raises(
            "update public.planning_occurrence set handled_at = %(h)s where id = %(id)s",
            {"h": "2026-09-30T10:00:00+08:00", "id": occ},
            "confirmed handling instant is immutable once written",
        )

    def test_closed_label_corrections_allowed_both_directions(self):
        # B5：completed ↔ discarded 双向更正合法；更正不改写 closed_at
        # （B7），handled_at 历史事实保持；completed → discarded_this 亦通。
        occ = self._fresh_occurrence(
            round_key="cycle:2026-10-03", schedule_date="2026-10-03",
            status="completed", closed_at="2026-10-03T09:00:00+08:00",
            handled_at="2026-09-30T09:00:00+08:00",
        )
        self._query(
            "update public.planning_occurrence set status = 'discarded' where id = %(id)s",
            {"id": occ},
        )
        row = self._query(
            "select status, closed_at, handled_at from public.planning_occurrence where id = %(id)s",
            {"id": occ},
        )[0]
        assert row[0] == "discarded"
        assert row[1].isoformat() == "2026-10-03T09:00:00+08:00"  # closed_at 保留
        assert row[2].isoformat() == "2026-09-30T09:00:00+08:00"  # handled_at 保留
        self._query(
            "update public.planning_occurrence set status = 'completed' where id = %(id)s",
            {"id": occ},
        )
        row = self._query(
            "select status, closed_at, handled_at from public.planning_occurrence where id = %(id)s",
            {"id": occ},
        )[0]
        assert row[0] == "completed"
        assert row[1].isoformat() == "2026-10-03T09:00:00+08:00"
        self._query(
            "update public.planning_occurrence set status = 'discarded_this' where id = %(id)s",
            {"id": occ},
        )
        assert self._query(
            "select status from public.planning_occurrence where id = %(id)s",
            {"id": occ},
        )[0][0] == "discarded_this"

    def test_discarded_without_handled_fact_can_gain_it_on_correction(self):
        # 整任务废弃历史（无 handled_at）更正为 completed：以更正时刻补记
        # 处理事实（从 null 写入允许；已有事实不可改写）。
        occ = self._fresh_occurrence(
            round_key="cycle:2026-10-04", schedule_date="2026-10-04",
            status="discarded", closed_at="2026-10-04T09:00:00+08:00",
        )
        self._query(
            "update public.planning_occurrence set status = 'completed', "
            "handled_at = %(h)s where id = %(id)s",
            {"h": "2026-10-05T10:00:00+08:00", "id": occ},
        )
        assert self._query(
            "select handled_at from public.planning_occurrence where id = %(id)s",
            {"id": occ},
        )[0][0].isoformat() == "2026-10-05T10:00:00+08:00"

    def test_discarded_this_to_completed_correction_allowed(self):
        # H2：discarded_this → completed 历史更正合法（Python 与数据库同模型）；
        # closed_at 与 handled_at 历史事实保持。
        occ = self._fresh_occurrence(
            round_key="cycle:2026-10-05", schedule_date="2026-10-05",
            status="discarded_this", closed_at="2026-10-05T09:00:00+08:00",
            handled_at="2026-10-05T09:00:00+08:00",
        )
        self._query(
            "update public.planning_occurrence set status = 'completed' where id = %(id)s",
            {"id": occ},
        )
        row = self._query(
            "select status, closed_at, handled_at from public.planning_occurrence where id = %(id)s",
            {"id": occ},
        )[0]
        assert row[0] == "completed"
        assert row[1].isoformat() == "2026-10-05T09:00:00+08:00"
        assert row[2].isoformat() == "2026-10-05T09:00:00+08:00"

    def test_timeout_cannot_be_completed_directly(self):
        # L1：数据库直接 SQL 也不允许 timeout → completed（与业务层同规则）。
        occ = self._fresh_occurrence(
            round_key="cycle:2026-10-06", schedule_date="2026-10-06",
            status="timeout", closed_at="2026-10-06T12:00:00+08:00",
        )
        # CHECK（不可延迟）先于延迟触发器触发：completed ⇒ handled_at 非空
        # 在 timeout 行（handled_at 必空）上必然违反，拒绝同样确定。
        with self.assertRaises(psycopg.errors.CheckViolation):
            self._query(
                "update public.planning_occurrence set status = 'completed' where id = %(id)s",
                {"id": occ},
            )

    def test_extra_early_completion_unique_per_period(self):
        # H5：同一任务同一固定刷新周期的额外完成记录，数据库唯一约束兜底
        # 并发窗口；不同周期不受影响。
        task_id = self._query(
            """
            insert into public.planning_task (
                content, task_type, time_mode, estimated_minutes, is_active,
                interval_days, refresh_mode, refresh_enabled, refresh_anchor_at,
                created_at, updated_at
            ) values (
                '间歇', 'interval', 'duration', 30, true,
                3, 'fixed_interval', true, '2026-09-24T06:00:00+08:00',
                '2026-09-24T06:00:00+08:00', '2026-09-24T06:00:00+08:00'
            ) returning id;
            """
        )[0][0]
        self._query(
            """
            insert into public.planning_occurrence (
                task_id, for_date, round_key, schedule_date, display_cycle_date,
                display_reason, status, closed_at, handled_at, sort_order,
                estimated_time_source, fixed_source, schedule_managed, source,
                early_period_date, generation_request_key,
                content_snapshot, display_content, time_mode_snapshot,
                created_at, updated_at
            ) values (
                %(task_id)s, '2026-09-24', 'early:2026-09-24:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                '2026-09-24', '2026-09-24', 'initial', 'completed',
                '2026-09-24T10:00:00+08:00', '2026-09-24T10:00:00+08:00', 40,
                'unassigned', null, true, 'early', '2026-09-24', 'k1',
                '间歇', '间歇', 'duration',
                '2026-09-24T10:00:00+08:00', '2026-09-24T10:00:00+08:00'
            );
            """,
            {"task_id": task_id},
        )
        with self.assertRaises(psycopg.errors.UniqueViolation):
            self._query(
                """
                insert into public.planning_occurrence (
                    task_id, for_date, round_key, schedule_date, display_cycle_date,
                    display_reason, status, closed_at, handled_at, sort_order,
                    estimated_time_source, fixed_source, schedule_managed, source,
                    early_period_date, generation_request_key,
                    content_snapshot, display_content, time_mode_snapshot,
                    created_at, updated_at
                ) values (
                    %(task_id)s, '2026-09-25', 'early:2026-09-25:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
                    '2026-09-25', '2026-09-25', 'initial', 'completed',
                    '2026-09-25T10:00:00+08:00', '2026-09-25T10:00:00+08:00', 40,
                    'unassigned', null, true, 'early', '2026-09-24', 'k2',
                    '间歇', '间歇', 'duration',
                    '2026-09-25T10:00:00+08:00', '2026-09-25T10:00:00+08:00'
                );
                """,
                {"task_id": task_id},
            )
        # 下一周期（不同 early_period_date）允许新增
        self._query(
            """
            insert into public.planning_occurrence (
                task_id, for_date, round_key, schedule_date, display_cycle_date,
                display_reason, status, closed_at, handled_at, sort_order,
                estimated_time_source, fixed_source, schedule_managed, source,
                early_period_date, generation_request_key,
                content_snapshot, display_content, time_mode_snapshot,
                created_at, updated_at
            ) values (
                %(task_id)s, '2026-09-27', 'early:2026-09-27:cccccccccccccccccccccccccccccccc',
                '2026-09-27', '2026-09-27', 'initial', 'completed',
                '2026-09-27T10:00:00+08:00', '2026-09-27T10:00:00+08:00', 40,
                'unassigned', null, true, 'early', '2026-09-27', 'k3',
                '间歇', '间歇', 'duration',
                '2026-09-27T10:00:00+08:00', '2026-09-27T10:00:00+08:00'
            );
            """,
            {"task_id": task_id},
        )
        assert self._query(
            "select count(*) from public.planning_occurrence where source = 'early' and task_id = %(id)s",
            {"id": task_id},
        )[0][0] == 2

    def test_reschedule_request_key_unique_on_task(self):
        # 模型 A：请求身份在任务行上唯一，并发重放收敛。
        task_id = self._task_id()
        self._query(
            "insert into public.planning_task (content, task_type, time_mode, estimated_minutes, "
            "is_active, refresh_mode, refresh_enabled, request_key, created_at, updated_at) "
            "values ('替代', 'once', 'duration', 30, true, 'none', true, "
            "'reschedule:99:k1', '2026-09-24T10:00:00+08:00', '2026-09-24T10:00:00+08:00')",
        )
        with self.assertRaises(psycopg.errors.UniqueViolation):
            self._query(
                "insert into public.planning_task (content, task_type, time_mode, estimated_minutes, "
                "is_active, refresh_mode, refresh_enabled, request_key, created_at, updated_at) "
                "values ('替代2', 'once', 'duration', 30, true, 'none', true, "
                "'reschedule:99:k1', '2026-09-24T10:00:01+08:00', '2026-09-24T10:00:01+08:00')",
            )

    def test_fixed_early_requires_period_identity(self):
        # N6：固定刷新型 source='early' 不得以 NULL early_period_date 绕过
        # (task_id, early_period_date) 唯一约束。
        task_id = self._query(
            """
            insert into public.planning_task (
                content, task_type, time_mode, estimated_minutes, is_active,
                interval_days, refresh_mode, refresh_enabled, refresh_anchor_at,
                created_at, updated_at
            ) values (
                '间歇', 'interval', 'duration', 30, true,
                3, 'fixed_interval', true, '2026-09-24T06:00:00+08:00',
                '2026-09-24T06:00:00+08:00', '2026-09-24T06:00:00+08:00'
            ) returning id;
            """
        )[0][0]
        self._assert_raises(
            """
            insert into public.planning_occurrence (
                task_id, for_date, round_key, schedule_date, display_cycle_date,
                display_reason, status, closed_at, handled_at, sort_order,
                estimated_time_source, fixed_source, schedule_managed, source,
                early_period_date, content_snapshot, display_content,
                time_mode_snapshot, created_at, updated_at
            ) values (
                %(task_id)s, '2026-09-24', 'early:2026-09-24:dddddddddddddddddddddddddddddddd',
                '2026-09-24', '2026-09-24', 'initial', 'completed',
                '2026-09-24T10:00:00+08:00', '2026-09-24T10:00:00+08:00', 40,
                'unassigned', null, true, 'early', null,
                '间歇', '间歇', 'duration',
                '2026-09-24T10:00:00+08:00', '2026-09-24T10:00:00+08:00'
            );
            """,
            {"task_id": task_id},
            "fixed-refresh early completion requires a period identity",
        )

    def test_reschedule_request_state_terminal_guards(self):
        # 第六轮 I1：request_state 终态不可逆——completed/superseded 不得
        # 回退 pending，superseded 不得转 completed；superseded ⇒ inactive。
        task_id = self._query(
            """
            insert into public.planning_task (
                content, task_type, time_mode, estimated_minutes, is_active,
                refresh_mode, refresh_enabled, request_key, request_est_start,
                request_state, created_at, updated_at
            ) values (
                '替代', 'once', 'duration', 30, false,
                'none', true, 'reschedule:88:k1', '2026-10-07T18:00:00+08:00',
                'superseded', '2026-10-07T15:00:00+08:00', '2026-10-07T15:00:00+08:00'
            ) returning id;
            """
        )[0][0]
        # superseded → pending 拒绝
        self._assert_raises(
            "update public.planning_task set request_state = 'pending' where id = %(id)s",
            {"id": task_id},
            "reschedule request state is terminal",
        )
        # superseded → completed 拒绝
        self._assert_raises(
            "update public.planning_task set request_state = 'completed' where id = %(id)s",
            {"id": task_id},
            "reschedule request state is terminal",
        )
        # superseded ⇒ inactive：特权启用 + 保持 superseded 组合被 CHECK 拒绝
        with self.assertRaises(psycopg.errors.CheckViolation):
            self._query(
                "update public.planning_task set is_active = true where id = %(id)s",
                {"id": task_id},
            )
        # pending → completed 合法
        ok_id = self._query(
            """
            insert into public.planning_task (
                content, task_type, time_mode, estimated_minutes, is_active,
                refresh_mode, refresh_enabled, request_key, request_est_start,
                request_state, created_at, updated_at
            ) values (
                '替代2', 'once', 'duration', 30, true,
                'none', true, 'reschedule:88:k2', '2026-10-07T18:00:00+08:00',
                'pending', '2026-10-07T15:00:00+08:00', '2026-10-07T15:00:00+08:00'
            ) returning id;
            """
        )[0][0]
        self._query(
            "update public.planning_task set request_state = 'completed' where id = %(id)s",
            {"id": ok_id},
        )
        # completed → pending 拒绝（终态回退）
        self._assert_raises(
            "update public.planning_task set request_state = 'pending' where id = %(id)s",
            {"id": ok_id},
            "reschedule request state is terminal",
        )

    def test_early_period_identity_survives_update_lifecycle(self):
        # M5：early_period_date 在整个生命周期内非空且不可变——
        # UPDATE NULL / UPDATE 改周期均拒绝；普通 schedule 行不受误伤。
        task_id = self._query(
            """
            insert into public.planning_task (
                content, task_type, time_mode, estimated_minutes, is_active,
                interval_days, refresh_mode, refresh_enabled, refresh_anchor_at,
                created_at, updated_at
            ) values (
                '间歇', 'interval', 'duration', 30, true,
                3, 'fixed_interval', true, '2026-10-07T06:00:00+08:00',
                '2026-10-07T06:00:00+08:00', '2026-10-07T06:00:00+08:00'
            ) returning id;
            """
        )[0][0]
        occ = self._fresh_occurrence(
            task_id=task_id,
            round_key="early:2026-10-07:eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
            schedule_date="2026-10-07", status="completed",
            closed_at="2026-10-07T10:00:00+08:00",
            handled_at="2026-10-07T10:00:00+08:00",
        )
        # 直接 SQL 把该行改成 schedule 轮 → 身份不可变守卫拒绝（含 source）
        self._assert_raises(
            "update public.planning_occurrence set source = 'schedule', "
            "early_period_date = null where id = %(id)s",
            {"id": occ},
            "business round identity is immutable",
        )
        # UPDATE NULL → 拒绝：非空检查（M5 前置）先触发，消息不同但同样拒绝
        self._assert_raises(
            "update public.planning_occurrence set early_period_date = null where id = %(id)s",
            {"id": occ},
            "fixed-refresh early completion requires a period identity",
        )
        # UPDATE 改周期 → 拒绝
        self._assert_raises(
            "update public.planning_occurrence set early_period_date = '2026-10-08' "
            "where id = %(id)s",
            {"id": occ},
            "early completion period identity is immutable",
        )
        # 普通 schedule 行更新不受误伤（daily 任务 + cycle 键）
        normal = self._fresh_occurrence(
            task_id=1, round_key="cycle:2026-10-08", schedule_date="2026-10-08")
        self._query(
            "update public.planning_occurrence set status = 'in_progress' "
            "where id = %(id)s",
            {"id": normal},
        )
        assert self._query(
            "select status from public.planning_occurrence where id = %(id)s",
            {"id": normal},
        )[0][0] == "in_progress"

    def test_round_identity_is_immutable(self):
        occ = self._fresh_occurrence(round_key="cycle:2026-10-01", schedule_date="2026-10-01")
        # 一致性字段一起改（for_date/round_key 跟随），绕开 CHECK 后仍被
        # 触发器的身份不可变守卫拒绝。
        self._assert_raises(
            "update public.planning_occurrence set schedule_date = '2026-10-02', "
            "for_date = '2026-10-02', round_key = 'cycle:2026-10-02', "
            "display_cycle_date = '2026-10-02' where id = %(id)s",
            {"id": occ},
            "business round identity is immutable",
        )

    # -- 第七轮：BF5 生成快照 / BF2+BF4 接管守卫 / BF3 30 分钟窗口 ----------

    def test_generation_snapshots_required_for_round_rows(self):
        # BF5：round_key 行必须携带生成时快照（内容 / 展示 / time_mode），
        # 且 is_limited 与 deadline_at 成对——缺快照的新版行直接被 CHECK 拒绝。
        with self.assertRaises(psycopg.errors.CheckViolation):
            self._query(
                """
                insert into public.planning_occurrence (
                    task_id, for_date, round_key, schedule_date, display_cycle_date,
                    display_reason, status, sort_order, is_fixed,
                    estimated_time_source, fixed_source, schedule_managed,
                    is_limited, source, created_at, updated_at
                ) values (
                    %(task_id)s, '2026-10-09', 'cycle:2026-10-09', '2026-10-09',
                    '2026-10-09', 'initial', 'pending', 20, false, 'unassigned',
                    null, true, false, 'schedule',
                    '2026-10-09T06:00:00+08:00', '2026-10-09T06:00:00+08:00'
                );
                """,
                {"task_id": self._task_id()},
            )

    def _reschedule_task(self, source_occ, key_suffix, **overrides):
        params = {
            "source": source_occ,
            "key": f"reschedule:{source_occ}:{key_suffix}",
            "state": overrides.pop("state", "pending"),
            "active": overrides.pop("active", "true"),
        }
        params.update(overrides)
        return self._query(
            """
            insert into public.planning_task (
                content, task_type, time_mode, estimated_minutes, is_active,
                refresh_mode, refresh_enabled, target_date, request_key,
                request_est_start, request_state, request_source_occurrence_id,
                created_at, updated_at
            ) values (
                '替代', 'once', 'duration', 30, %(active)s,
                'none', true, '2026-10-10', %(key)s,
                '2026-10-10T18:00:00+08:00', %(state)s, %(source)s,
                '2026-10-07T15:00:00+08:00', '2026-10-07T15:00:00+08:00'
            ) returning id;
            """,
            params,
        )[0][0]

    def test_reschedule_todo_guard_allows_single_current_todo(self):
        # BF2/BF4：同一旧超时实例同时只允许一个当前业务待办（pending 请求
        # 或开放实例）。第一个请求落库成功；并发 / 顺序的第二个当前待办
        # 被数据库拒绝（应用层随即将其收敛到接管路径）。
        source_occ = self._fresh_occurrence(
            round_key="cycle:2026-10-11", schedule_date="2026-10-11")
        first = self._reschedule_task(source_occ, "k1")
        with self.assertRaises(psycopg.errors.RaiseException) as caught:
            self._reschedule_task(source_occ, "k2")
        self.assertIn(
            "another reschedule todo for this timeout is still current",
            str(caught.exception),
        )
        # 请求键与来源必须一致
        with self.assertRaises(psycopg.errors.RaiseException) as caught:
            self._reschedule_task(999999, "k3", key=f"reschedule:{source_occ}:k3")
        self.assertIn("reschedule request source must match its request key",
                      str(caught.exception))
        # 前一业务待办正常关闭（请求 completed + 实例关闭）→ 槽位释放，
        # 再次重排属于新的业务安排，允许新建
        self._query(
            "update public.planning_task set request_state = 'completed' "
            "where id = %(id)s",
            {"id": first},
        )
        self._query(
            "update public.planning_occurrence set status = 'completed', "
            "closed_at = '2026-10-10T19:00:00+08:00', "
            "handled_at = '2026-10-10T19:00:00+08:00' "
            "where task_id = %(id)s",
            {"id": first},
        )
        second = self._reschedule_task(source_occ, "k4")
        self.assertIsNotNone(second)

    def test_adopt_identity_cas_pattern_on_real_postgres(self):
        # C-1：双连接真 PostgreSQL 验证 adopt 身份 CAS 模式——基于过期读取
        # 的条件更新必然 0 行命中（丢更新被数据库拒绝）；失败方重读后以
        # 最新键 CAS 登记 absorbed，全部请求键保持可追踪。
        source_occ = self._fresh_occurrence(
            round_key="cycle:2026-10-16", schedule_date="2026-10-16")
        task_id = self._reschedule_task(source_occ, "k1", state="completed")
        self._query(
            "update public.planning_task set request_absorbed_keys = '{}' where id = %(id)s",
            {"id": task_id},
        )
        uri = self.server.get_uri()
        conn_a = psycopg.connect(uri, autocommit=True)
        conn_b = psycopg.connect(uri, autocommit=True)
        key1 = f"reschedule:{source_occ}:k1"
        key_a = f"reschedule:{source_occ}:kA"
        key_b = f"reschedule:{source_occ}:kB"
        try:
            select_sql = (
                "select request_key, request_absorbed_keys from public.planning_task "
                "where id = %(id)s"
            )
            row_a = conn_a.execute(select_sql, {"id": task_id}).fetchone()
            row_b = conn_b.execute(select_sql, {"id": task_id}).fetchone()
            assert row_a[0] == key1 and row_b[0] == key1  # 双方读到同一现状

            # B 先提交身份 CAS：赢得接管
            won_b = conn_b.execute(
                "update public.planning_task set request_key = %(new)s, "
                "request_absorbed_keys = %(abs)s "
                "where id = %(id)s and request_key = %(expected)s returning id",
                {"new": key_b, "abs": [key1], "id": task_id, "expected": key1},
            ).fetchall()
            assert len(won_b) == 1

            # A 基于过期读取提交同一条件的 CAS：必须 0 行命中
            lost_a = conn_a.execute(
                "update public.planning_task set request_key = %(new)s, "
                "request_absorbed_keys = %(abs)s "
                "where id = %(id)s and request_key = %(expected)s returning id",
                {"new": key_a, "abs": [key1], "id": task_id, "expected": key1},
            ).fetchall()
            assert lost_a == [], "stale CAS must not overwrite the newer identity"

            # A 重读最新状态 → stand-down：以最新键为条件的 absorbed 登记
            fresh = conn_a.execute(select_sql, {"id": task_id}).fetchone()
            assert fresh[0] == key_b
            absorbed = list(fresh[1] or []) + [key_a]
            registered = conn_a.execute(
                "update public.planning_task set request_absorbed_keys = %(abs)s "
                "where id = %(id)s and request_key = %(expected)s returning id",
                {"abs": absorbed, "id": task_id, "expected": fresh[0]},
            ).fetchall()
            assert len(registered) == 1

            final = conn_a.execute(select_sql, {"id": task_id}).fetchone()
            assert final[0] == key_b
            assert set(final[1] or []) >= {key1, key_a}, "no key may vanish"
        finally:
            conn_a.close()
            conn_b.close()

    # -- 最终并发收口（F1 / F2）真 PostgreSQL 双连接验证 --------------------

    _ABSORB_SQL = (
        "select public.planning_absorb_reschedule_request("
        "%(task_id)s, %(key)s, %(now)s)"
    )
    _TAKEOVER_SQL = (
        "select public.planning_takeover_reschedule_request("
        "%(task_id)s, %(new_key)s, %(new_start)s, %(expected)s, %(now)s)"
    )

    def _task_identity(self, task_id):
        row = self._query(
            "select request_key, request_absorbed_keys from public.planning_task "
            "where id = %(id)s",
            {"id": task_id},
        )[0]
        return row[0], set(row[1] or [])

    def test_f2_e2_dual_standdown_registrations_merge(self):
        # E2：两个 stand-down 并发登记不同 absorbed 键——后到者的原子合并
        # 在行锁下读取已提交的最新数组（READ COMMITTED 重评估），先登记的
        # 键不被覆盖；两个键都保留。
        source_occ = self._fresh_occurrence(
            round_key="cycle:2026-10-17", schedule_date="2026-10-17")
        task_id = self._reschedule_task(source_occ, "kA", state="completed")
        key1 = f"reschedule:{source_occ}:k1"
        key_b = f"reschedule:{source_occ}:kB"
        key_c = f"reschedule:{source_occ}:kC"
        self._query(
            "update public.planning_task set request_absorbed_keys = %(abs)s "
            "where id = %(id)s",
            {"abs": [key1], "id": task_id},
        )
        uri = self.server.get_uri()
        conn_b = psycopg.connect(uri)
        conn_c = psycopg.connect(uri)
        params_b = {"task_id": task_id, "key": key_b, "now": REPRO_NOW}
        params_c = {"task_id": task_id, "key": key_c, "now": REPRO_NOW}
        try:
            result_b = conn_b.execute(self._ABSORB_SQL, params_b).fetchone()
            assert result_b == (True,)  # B 登记成功，未提交（持有行锁）
            outcome = {}

            def register_c():
                try:
                    outcome["result"] = conn_c.execute(
                        self._ABSORB_SQL, params_c).fetchone()
                except Exception as exc:  # noqa: BLE001
                    outcome["error"] = exc

            worker = threading.Thread(target=register_c)
            worker.start()
            time.sleep(1.0)
            self.assertTrue(worker.is_alive(),
                            "C must block on the row lock while B is uncommitted")
            conn_b.commit()  # B 提交 → C 的合并读取到 [k1, kB]
            worker.join(timeout=10)
            self.assertFalse(worker.is_alive())
            self.assertEqual(outcome.get("result"), (True,))
            conn_c.commit()
            current, absorbed = self._task_identity(task_id)
            assert current.endswith(":kA")
            assert {key1, key_b, key_c} <= absorbed, "no key may vanish"
        finally:
            conn_b.close()
            conn_c.close()

    def test_f2_e2b_dual_adopt_vs_standdown_merge(self):
        # E2b：adopt 身份接管与 stand-down 登记并发——接管提交后，被阻塞
        # 的登记在新行版本上重评估（键=kD、absorbed=[k1,kA]）并继续合并；
        # 接管方与登记方的键都保留。
        source_occ = self._fresh_occurrence(
            round_key="cycle:2026-10-18", schedule_date="2026-10-18")
        task_id = self._reschedule_task(source_occ, "kA", state="completed")
        key1 = f"reschedule:{source_occ}:k1"
        key_a = f"reschedule:{source_occ}:kA"
        key_d = f"reschedule:{source_occ}:kD"
        key_e = f"reschedule:{source_occ}:kE"
        self._query(
            "update public.planning_task set request_absorbed_keys = %(abs)s "
            "where id = %(id)s",
            {"abs": [key1], "id": task_id},
        )
        uri = self.server.get_uri()
        conn_d = psycopg.connect(uri)
        conn_e = psycopg.connect(uri)
        try:
            result_d = conn_d.execute(self._TAKEOVER_SQL, {
                "task_id": task_id, "new_key": key_d,
                "new_start": "2026-10-18T21:00:00+08:00",
                "expected": key_a, "now": REPRO_NOW,
            }).fetchone()
            assert result_d == (True,)  # 接管成功，未提交（持有行锁）
            outcome = {}

            def register_e():
                try:
                    outcome["result"] = conn_e.execute(self._ABSORB_SQL, {
                        "task_id": task_id, "key": key_e, "now": REPRO_NOW,
                    }).fetchone()
                except Exception as exc:  # noqa: BLE001
                    outcome["error"] = exc

            worker = threading.Thread(target=register_e)
            worker.start()
            time.sleep(1.0)
            self.assertTrue(worker.is_alive(),
                            "stand-down must block while adopt is uncommitted")
            conn_d.commit()
            worker.join(timeout=10)
            self.assertFalse(worker.is_alive())
            self.assertEqual(outcome.get("result"), (True,))
            conn_e.commit()
            current, absorbed = self._task_identity(task_id)
            assert current.endswith(":kD")
            assert {key1, key_a, key_e} <= absorbed, "no key may vanish"
        finally:
            conn_d.close()
            conn_e.close()

    def test_f1_e3_creator_side_effects_invalidated_after_takeover(self):
        # E3：创建者 vs 接管者——接管（身份 CAS）后，旧创建请求的全部剩余
        # 副作用在数据库侧失效：锚定标记守卫拒绝其锚定写入；completed CAS
        #（state + request_key 双条件）0 行命中；键感知资格检查为 False。
        source_occ = self._fresh_occurrence(
            round_key="cycle:2026-10-19", schedule_date="2026-10-19")
        task_id = self._reschedule_task(source_occ, "kA", state="pending")
        key_a = f"reschedule:{source_occ}:kA"
        key_b = f"reschedule:{source_occ}:kB"
        creator_occ = self._fresh_occurrence(
            task_id=task_id, round_key="once", schedule_date="2026-10-19")
        # B 接管身份（应用层 adopt 的数据库效果）
        self._query(self._TAKEOVER_SQL, {
            "task_id": task_id, "new_key": key_b,
            "new_start": "2026-10-19T20:00:00+08:00",
            "expected": key_a, "now": REPRO_NOW,
        })
        # A 的锚定写入（marker=kA，任务身份已是 kB）→ 触发器拒绝
        self._assert_raises(
            "update public.planning_occurrence set generation_request_key = %(marker)s, "
            "est_start = '2026-10-19T19:00:00+08:00', "
            "est_end = '2026-10-19T19:30:00+08:00', "
            "estimated_time_source = 'manual', fixed_source = 'manual', "
            "schedule_managed = false, is_fixed = true "
            "where id = %(id)s",
            {"marker": key_a, "id": creator_occ},
            "reschedule anchor marker must match the current request identity",
        )
        # A 的 completed CAS（state + key 双条件）→ 0 行命中
        landed = self._query(
            "update public.planning_task set request_state = 'completed' "
            "where id = %(id)s and request_state = 'pending' and request_key = %(key)s "
            "returning id",
            {"id": task_id, "key": key_a},
        )
        assert landed == [], "stale creator must not advance the request lifecycle"
        # 键感知资格检查（应用层 _reschedule_still_pending 的谓词）为 False
        state, current_key = self._query(
            "select request_state, request_key from public.planning_task where id = %(id)s",
            {"id": task_id},
        )[0]
        assert (state, current_key) == ("pending", key_b)
        # B 的合法锚定（marker=当前键）放行；completed CAS（双条件）命中
        self._query(
            "update public.planning_occurrence set generation_request_key = %(marker)s "
            "where id = %(id)s",
            {"marker": key_b, "id": creator_occ},
        )
        landed_b = self._query(
            "update public.planning_task set request_state = 'completed' "
            "where id = %(id)s and request_state = 'pending' and request_key = %(key)s "
            "returning id",
            {"id": task_id, "key": key_b},
        )
        assert len(landed_b) == 1

    def test_anchor_trigger_leaves_non_reschedule_claims_untouched(self):
        # 锚定标记守卫只约束重排任务（任务行带 request_key）：普通任务的
        # 提前完成幂等键标记（request_key 为 NULL）不受影响。
        normal_occ = self._fresh_occurrence(
            task_id=self._task_id(),
            round_key="cycle:2026-10-21", schedule_date="2026-10-21")
        self._query(
            "update public.planning_occurrence set generation_request_key = 'k-early' "
            "where id = %(id)s",
            {"id": normal_occ},
        )
        marker = self._query(
            "select generation_request_key from public.planning_occurrence where id = %(id)s",
            {"id": normal_occ},
        )[0][0]
        assert marker == "k-early"

    def test_after_completion_early_window_sequential(self):
        # BF3：30 分钟窗口内的第二条 after_completion 提前完成被数据库拒绝；
        # 窗口外（> 30 分钟）允许新的真实事实。
        task_id = self._query(
            """
            insert into public.planning_task (
                content, task_type, time_mode, estimated_minutes, is_active,
                interval_days, refresh_mode, refresh_enabled,
                created_at, updated_at
            ) values (
                '间歇', 'interval', 'duration', 30, true,
                3, 'after_completion', true,
                '2026-10-07T06:00:00+08:00', '2026-10-07T06:00:00+08:00'
            ) returning id;
            """
        )[0][0]

        def early_row(key, handled):
            return self._query(
                """
                insert into public.planning_occurrence (
                    task_id, for_date, round_key, schedule_date, display_cycle_date,
                    display_reason, status, closed_at, handled_at, sort_order,
                    estimated_time_source, fixed_source, schedule_managed, source,
                    early_period_date, generation_request_key,
                    content_snapshot, display_content, time_mode_snapshot,
                    created_at, updated_at
                ) values (
                    %(task_id)s, '2026-10-10',
                    'early:2026-10-10:' || %(key)s,
                    '2026-10-10', '2026-10-10', 'initial', 'completed',
                    %(handled)s, %(handled)s, 40,
                    'unassigned', null, true, 'early', null, %(key)s,
                    '间歇', '间歇', 'duration',
                    %(handled)s, %(handled)s
                ) returning id;
                """,
                {"task_id": task_id, "key": key, "handled": handled},
            )[0][0]

        early_row("a" * 32, "2026-10-10T08:00:00+08:00")
        with self.assertRaises(psycopg.errors.RaiseException) as caught:
            early_row("b" * 32, "2026-10-10T08:05:00+08:00")
        self.assertIn(
            "after_completion early completions within the same 30-minute window",
            str(caught.exception),
        )
        # 窗口外：新的真实提前完成
        second = early_row("c" * 32, "2026-10-10T08:31:00+08:00")
        self.assertIsNotNone(second)
        # 固定刷新型 early 携带周期身份，不受窗口触发器影响（同期唯一性
        # 仍由 (task_id, early_period_date) 唯一索引约束）
        fixed_id = self._query(
            """
            insert into public.planning_task (
                content, task_type, time_mode, estimated_minutes, is_active,
                interval_days, refresh_mode, refresh_enabled, refresh_anchor_at,
                created_at, updated_at
            ) values (
                '固定', 'interval', 'duration', 30, true,
                1, 'fixed_interval', true, '2026-10-07T06:00:00+08:00',
                '2026-10-07T06:00:00+08:00', '2026-10-07T06:00:00+08:00'
            ) returning id;
            """
        )[0][0]
        self._query(
            """
            insert into public.planning_occurrence (
                task_id, for_date, round_key, schedule_date, display_cycle_date,
                display_reason, status, closed_at, handled_at, sort_order,
                estimated_time_source, fixed_source, schedule_managed, source,
                early_period_date, generation_request_key,
                content_snapshot, display_content, time_mode_snapshot,
                created_at, updated_at
            ) values (
                %(task_id)s, '2026-10-12', 'early:2026-10-12:' || repeat('d', 32),
                '2026-10-12', '2026-10-12', 'initial', 'completed',
                '2026-10-12T09:00:00+08:00', '2026-10-12T09:00:00+08:00', 40,
                'unassigned', null, true, 'early', '2026-10-12', 'e1',
                '固定', '固定', 'duration',
                '2026-10-12T09:00:00+08:00', '2026-10-12T09:00:00+08:00'
            );
            """,
            {"task_id": fixed_id},
        )
        self._query(
            """
            insert into public.planning_occurrence (
                task_id, for_date, round_key, schedule_date, display_cycle_date,
                display_reason, status, closed_at, handled_at, sort_order,
                estimated_time_source, fixed_source, schedule_managed, source,
                early_period_date, generation_request_key,
                content_snapshot, display_content, time_mode_snapshot,
                created_at, updated_at
            ) values (
                %(task_id)s, '2026-10-12', 'early:2026-10-12:' || repeat('f', 32),
                '2026-10-12', '2026-10-12', 'initial', 'completed',
                '2026-10-12T09:00:00+08:00', '2026-10-12T09:00:00+08:00', 40,
                'unassigned', null, true, 'early', '2026-10-13', 'e2',
                '固定', '固定', 'duration',
                '2026-10-12T09:00:00+08:00', '2026-10-12T09:00:00+08:00'
            );
            """,
            {"task_id": fixed_id},
        )

    def test_after_completion_early_window_concurrent_connections(self):
        # BF3/G：真实 PostgreSQL 上两个不同 key 的并发提前完成——advisory
        # lock 把后到者的窗口检查串行化到先到事务提交之后，只允许一次有效
        # 完成推进。
        task_id = self._query(
            """
            insert into public.planning_task (
                content, task_type, time_mode, estimated_minutes, is_active,
                interval_days, refresh_mode, refresh_enabled,
                created_at, updated_at
            ) values (
                '间歇', 'interval', 'duration', 30, true,
                3, 'after_completion', true,
                '2026-10-07T06:00:00+08:00', '2026-10-07T06:00:00+08:00'
            ) returning id;
            """
        )[0][0]
        uri = self.server.get_uri()
        conn_a = psycopg.connect(uri)  # 请求 A：先到，未提交（持有 advisory lock）
        conn_b = psycopg.connect(uri)  # 请求 B：后到
        insert_sql = """
            insert into public.planning_occurrence (
                task_id, for_date, round_key, schedule_date, display_cycle_date,
                display_reason, status, closed_at, handled_at, sort_order,
                estimated_time_source, fixed_source, schedule_managed, source,
                early_period_date, generation_request_key,
                content_snapshot, display_content, time_mode_snapshot,
                created_at, updated_at
            ) values (
                %(task_id)s, '2026-10-14',
                'early:2026-10-14:' || %(key)s,
                '2026-10-14', '2026-10-14', 'initial', 'completed',
                %(handled)s, %(handled)s, 40,
                'unassigned', null, true, 'early', null, %(key)s,
                '间歇', '间歇', 'duration',
                %(handled)s, %(handled)s
            );
            """
        outcome = {}

        def request_b():
            try:
                conn_b.execute(insert_sql, {
                    "task_id": task_id, "key": "b" * 32,
                    "handled": "2026-10-14T08:00:00.5+08:00",
                })
                outcome["inserted"] = True
            except Exception as exc:  # noqa: BLE001 - 任意数据库层拒绝都算收敛
                outcome["error"] = exc

        try:
            conn_a.execute(insert_sql, {
                "task_id": task_id, "key": "a" * 32,
                "handled": "2026-10-14T08:00:00+08:00",
            })
            worker = threading.Thread(target=request_b)
            worker.start()
            time.sleep(1.0)
            self.assertTrue(worker.is_alive(),
                            "B must block on the advisory lock while A is uncommitted")
            conn_a.commit()  # A 的成功事实提交 → B 的检查看到它并拒绝
            worker.join(timeout=10)
            self.assertFalse(worker.is_alive())
            self.assertNotIn("inserted", outcome)
            self.assertIn(
                "after_completion early completions within the same 30-minute window",
                str(outcome.get("error")),
            )
            conn_b.rollback()
            count = self._query(
                "select count(*) from public.planning_occurrence "
                "where task_id = %(id)s and source = 'early'",
                {"id": task_id},
            )[0][0]
            self.assertEqual(count, 1)
        finally:
            conn_a.close()
            conn_b.close()

    def test_hollow_round_requires_both_phases(self):
        # 约束触发器（deferrable initially deferred）在 autocommit 下逐语句生效；
        # 中空任务只写入单一阶段（即使补齐全部形状字段）也被拒绝。
        hollow_id = self._query("""
            insert into public.planning_task (
                content, task_type, time_mode, estimated_minutes, is_active,
                is_hollow, hollow_start_minutes, hollow_wait_minutes, hollow_end_minutes,
                refresh_mode, refresh_enabled, created_at, updated_at
            ) values (
                '煮饭', 'daily', 'duration', 10, true,
                true, 10, 30, 5,
                'daily', true, '2026-09-23T07:00:00+08:00', '2026-09-23T07:00:00+08:00'
            ) returning id;
        """)[0][0]
        self._assert_raises(
            """
            insert into public.planning_occurrence (
                task_id, for_date, round_key, schedule_date, display_cycle_date,
                display_reason, phase, phase_group, status, sort_order, is_fixed,
                estimated_time_source, fixed_source, schedule_managed, source,
                content_snapshot, display_content, time_mode_snapshot,
                created_at, updated_at
            ) values (
                %(task_id)s, '2026-10-02', 'cycle:2026-10-02', '2026-10-02', '2026-10-02',
                'initial', 'start',
                md5(%(task_text)s || ':cycle:2026-10-02')::uuid,
                'pending', 30, false, 'unassigned', null, true, 'schedule',
                '煮饭', '煮饭·开始', 'duration',
                '2026-10-02T06:00:00+08:00', '2026-10-02T06:00:00+08:00'
            );
            """,
            {"task_id": hollow_id, "task_text": str(hollow_id)},
            "hollow round requires both start and end phases",
        )

    # -- 批次 2：可安排时段窗口列与形状 CHECK（施工计划 §3.6：真库验证，
    #    本地语法解析不算数；既有 1A/1B 约束零回归由上方全部既有用例承担）

    def _windowed_task(self, start_tod=None, end_tod=None):
        """插入带模板窗口的任务定义，返回 id。"""
        return self._query(
            """
            insert into public.planning_task (
                content, task_type, time_mode, estimated_minutes, is_active,
                refresh_mode, refresh_enabled, window_start_tod, window_end_tod,
                created_at, updated_at
            ) values (
                '窗口任务', 'daily', 'duration', 30, true,
                'daily', true, %(start_tod)s, %(end_tod)s,
                '2026-09-27T07:00:00+08:00', '2026-09-27T07:00:00+08:00'
            ) returning id;
            """,
            {"start_tod": start_tod, "end_tod": end_tod},
        )[0][0]

    def test_template_window_four_combinations_are_accepted(self):
        # §18 四种组合均可落库：双端（含跨自然午夜 end < start 写法）/
        # 只有最早开始 / 只有最晚完成 / 两端皆空；各端独立为空合法。
        dual = self._windowed_task(_time(23, 0), _time(2, 0))
        earliest_only = self._windowed_task(_time(3, 0), None)
        latest_only = self._windowed_task(None, _time(22, 0))
        no_window = self._windowed_task(None, None)
        rows = {
            row[0]: (row[1], row[2])
            for row in self._query(
                "select id, window_start_tod, window_end_tod from public.planning_task "
                "where id = any(%(ids)s)",
                {"ids": [dual, earliest_only, latest_only, no_window]},
            )
        }
        assert rows[dual] == (_time(23, 0), _time(2, 0))
        assert rows[earliest_only] == (_time(3, 0), None)
        assert rows[latest_only] == (None, _time(22, 0))
        assert rows[no_window] == (None, None)

    def test_template_window_equal_endpoints_rejected(self):
        # start == end 拒绝（不解释为 24h，§6.7）。
        with self.assertRaises(psycopg.errors.CheckViolation):
            self._windowed_task(_time(3, 0), _time(3, 0))

    def test_windowed_task_generation_shape_satisfies_identity_check(self):
        # §3.2：新窗口行（is_limited=false、deadline_at=null、
        # estimated_time_source='unassigned'、est 成对为空、窗口成对冻结）
        # 天然满足 1A 身份 CHECK——模板窗口 + 实例冻结窗口成对落库零冲突。
        task_id = self._windowed_task(_time(18, 0), _time(22, 0))
        occ = self._fresh_occurrence(
            task_id=task_id, round_key="cycle:2026-10-22", schedule_date="2026-10-22",
            window_start_at="2026-10-22T18:00:00+08:00",
            window_end_at="2026-10-22T22:00:00+08:00",
        )
        row = self._query(
            "select window_start_at, window_end_at, is_limited, deadline_at, "
            "estimated_time_source, est_start, est_end "
            "from public.planning_occurrence where id = %(id)s",
            {"id": occ},
        )[0]
        assert row[0].isoformat() == "2026-10-22T18:00:00+08:00"
        assert row[1].isoformat() == "2026-10-22T22:00:00+08:00"
        assert row[2] is False and row[3] is None
        assert row[4] == "unassigned" and row[5] is None and row[6] is None

    def test_occurrence_window_four_combinations_are_accepted(self):
        # 实例窗口同四组合：单侧冻结后只有一端；NULL = 无该端约束。
        dual = self._fresh_occurrence(
            round_key="cycle:2026-10-23", schedule_date="2026-10-23",
            window_start_at="2026-10-23T23:00:00+08:00",
            window_end_at="2026-10-24T02:00:00+08:00",
        )
        earliest_only = self._fresh_occurrence(
            round_key="cycle:2026-10-24", schedule_date="2026-10-24",
            window_start_at="2026-10-24T03:00:00+08:00",
        )
        latest_only = self._fresh_occurrence(
            round_key="cycle:2026-10-25", schedule_date="2026-10-25",
            window_end_at="2026-10-25T22:00:00+08:00",
        )
        no_window = self._fresh_occurrence(
            round_key="cycle:2026-10-26", schedule_date="2026-10-26",
        )
        rows = {
            row[0]: (row[1], row[2])
            for row in self._query(
                "select id, window_start_at, window_end_at "
                "from public.planning_occurrence where id = any(%(ids)s) order by id",
                {"ids": [dual, earliest_only, latest_only, no_window]},
            )
        }
        assert rows[dual][0].isoformat() == "2026-10-23T23:00:00+08:00"
        assert rows[dual][1].isoformat() == "2026-10-24T02:00:00+08:00"
        assert rows[earliest_only][0].isoformat() == "2026-10-24T03:00:00+08:00"
        assert rows[earliest_only][1] is None
        assert rows[latest_only][0] is None
        assert rows[latest_only][1].isoformat() == "2026-10-25T22:00:00+08:00"
        assert rows[no_window] == (None, None)

    def test_occurrence_window_order_enforced_when_both_present(self):
        # 双端同时非空时要求 end > start（绝对瞬间）：相等与倒序均拒绝。
        with self.assertRaises(psycopg.errors.CheckViolation):
            self._fresh_occurrence(
                round_key="cycle:2026-10-27", schedule_date="2026-10-27",
                window_start_at="2026-10-27T05:00:00+08:00",
                window_end_at="2026-10-27T05:00:00+08:00",
            )
        with self.assertRaises(psycopg.errors.CheckViolation):
            self._fresh_occurrence(
                round_key="cycle:2026-10-28", schedule_date="2026-10-28",
                window_start_at="2026-10-28T05:00:00+08:00",
                window_end_at="2026-10-28T04:00:00+08:00",
            )

    def test_legacy_shape_rows_keep_null_windows_and_stay_valid(self):
        # 既有形状行为零回归：窗口列为 NULL 的 1A 行按原语义正常写入与更新。
        occ = self._fresh_occurrence(
            round_key="cycle:2026-10-29", schedule_date="2026-10-29")
        row = self._query(
            "select window_start_at, window_end_at from public.planning_occurrence "
            "where id = %(id)s",
            {"id": occ},
        )[0]
        assert row == (None, None)
        self._query(
            "update public.planning_occurrence set status = 'in_progress' "
            "where id = %(id)s",
            {"id": occ},
        )
        assert self._query(
            "select status from public.planning_occurrence where id = %(id)s",
            {"id": occ},
        )[0][0] == "in_progress"

    # -- 批次 2 复审修复轮：迁移重放行为（真实 pgserver 执行真实迁移文件，
    #    不是 SQL 字符串搜索；复审 LOW 项）--------------------------------

    def _window_migration_sql(self):
        return WINDOW_MIGRATION.read_text(encoding="utf-8")

    def _constraint_count(self, table, name):
        return self._query(
            "select count(*) from pg_constraint "
            "where conname = %(name)s and conrelid = %(table)s::regclass",
            {"name": name, "table": table},
        )[0][0]

    def _window_column_count(self):
        return self._query(
            "select count(*) from information_schema.columns "
            "where table_schema = 'public' and table_name in "
            "('planning_task', 'planning_occurrence') "
            "and column_name like 'window%'",
        )[0][0]

    def test_window_migration_replays_cleanly_on_same_database(self):
        # 同一临时 PostgreSQL 库连续执行真实窗口迁移两次均成功（重放安全）；
        # 两个 CHECK 在目标表上各只有一份；迁移不写任何数据行。
        rows_before = self._query(
            "select count(*) from public.planning_occurrence")[0][0]
        self._query(self._window_migration_sql())
        self._query(self._window_migration_sql())
        assert rows_before == self._query(
            "select count(*) from public.planning_occurrence")[0][0]
        assert self._constraint_count(
            "public.planning_task", "planning_task_window_tod_shape_check") == 1
        assert self._constraint_count(
            "public.planning_occurrence",
            "planning_occurrence_window_at_order_check") == 1

    def test_same_named_constraint_elsewhere_does_not_fool_scope_guard(self):
        # 重放守卫按 (conname, conrelid) 精确判定：先删除目标表上的两个
        # CHECK，再在其他表（public 与独立 schema）放置同名约束后重放真实
        # 迁移——目标表必须照常补回约束，不被同名 decoy 误判为已存在；
        # decoy 自身的同名约束不受影响。
        self._query(
            "alter table public.planning_task "
            "drop constraint planning_task_window_tod_shape_check")
        self._query(
            "alter table public.planning_occurrence "
            "drop constraint planning_occurrence_window_at_order_check")
        try:
            self._query(
                """
                create schema replay_probe;
                create table replay_probe.decoy (
                    id integer primary key,
                    constraint planning_task_window_tod_shape_check check (id > 0),
                    constraint planning_occurrence_window_at_order_check check (id > 0)
                );
                create table public.planning_window_replay_decoy (
                    id integer primary key,
                    constraint planning_task_window_tod_shape_check check (id > 0),
                    constraint planning_occurrence_window_at_order_check check (id > 0)
                );
                """
            )
            self._query(self._window_migration_sql())
            assert self._constraint_count(
                "public.planning_task", "planning_task_window_tod_shape_check") == 1
            assert self._constraint_count(
                "public.planning_occurrence",
                "planning_occurrence_window_at_order_check") == 1
            assert self._constraint_count(
                "replay_probe.decoy", "planning_task_window_tod_shape_check") == 1
            assert self._constraint_count(
                "public.planning_window_replay_decoy",
                "planning_occurrence_window_at_order_check") == 1
        finally:
            self._query("drop table if exists public.planning_window_replay_decoy")
            self._query("drop schema if exists replay_probe cascade")

    def _reset_window_schema(self):
        """把库还原到窗口迁移执行前的形状（先删 CHECK 再删列）。"""
        self._query(
            "alter table public.planning_task "
            "drop constraint planning_task_window_tod_shape_check")
        self._query(
            "alter table public.planning_occurrence "
            "drop constraint planning_occurrence_window_at_order_check")
        self._query(
            "alter table public.planning_task "
            "drop column window_start_tod, drop column window_end_tod")
        self._query(
            "alter table public.planning_occurrence "
            "drop column window_start_at, drop column window_end_at")

    def _run_migration_statement_by_statement(self, sql, conn):
        """按迁移文件顶层语句逐条发送（显式 begin / commit 照原样执行）。"""
        for statement in _split_top_level_statements(sql):
            conn.execute(statement)

    def test_interrupted_window_migration_leaves_no_half_state(self):
        # 事务失败无半状态，且原子性必须来自迁移文件自身的显式 BEGIN/COMMIT：
        # 逐**顶层语句**发送（而非整串 Simple Query——后者会自带隐式事务，
        # 掩盖文件缺少显式事务边界的缺陷）。先把库还原到「迁移前」形状，
        # 另一连接持 planning_occurrence 排他锁，逐条执行至
        # planning_occurrence 加列语句时被 statement_timeout 取消——已执行
        # 的前半段（planning_task 加列与约束）随文件显式 BEGIN 开启的事务
        # 整体回滚；锁释放后逐条完整重放成功。
        self._reset_window_schema()
        statements = _split_top_level_statements(self._window_migration_sql())
        # 文件自身的显式事务边界必须按真实顺序出现在执行序列里
        assert statements[0].casefold() == "begin"
        assert statements[-1].casefold() == "commit"
        locker = psycopg.connect(self.server.get_uri(), autocommit=True)
        runner = psycopg.connect(self.server.get_uri(), autocommit=True)
        try:
            locker.execute("begin")
            locker.execute(
                "lock table public.planning_occurrence in access exclusive mode")
            runner.execute("set statement_timeout = '1s'")
            with self.assertRaises(psycopg.errors.QueryCanceled):
                for statement in statements:
                    runner.execute(statement)
            runner.execute("rollback")  # 清除服务器端被中止的事务
            # 取消发生在 planning_occurrence 加列：前半段不得残留
            assert self._window_column_count() == 0
            assert self._constraint_count(
                "public.planning_task", "planning_task_window_tod_shape_check") == 0
            assert self._constraint_count(
                "public.planning_occurrence",
                "planning_occurrence_window_at_order_check") == 0
        finally:
            runner.close()
            locker.execute("rollback")  # 释放排他锁
            locker.close()
        # 锁释放后逐条完整重放：列与约束全部落位（各恰好一份）
        self._run_migration_statement_by_statement(
            self._window_migration_sql(), self.conn)
        assert self._window_column_count() == 4
        assert self._constraint_count(
            "public.planning_task", "planning_task_window_tod_shape_check") == 1
        assert self._constraint_count(
            "public.planning_occurrence",
            "planning_occurrence_window_at_order_check") == 1

    def test_interrupted_atomicity_comes_from_migration_explicit_transaction(self):
        # 常驻变异守卫：从执行序列中剔除迁移文件自身的 BEGIN/COMMIT（内存
        # 变异，磁盘文件不动），以同样的逐顶层语句方式在同一故障点中断
        # ——前半段 DDL 必然残留（planning_task 2 列 + 1 CHECK，与独立
        # 复现一致），即「0 残留」断言在变异下必然失败。若执行方式退回
        # 整串 Simple Query（隐式事务兜底），本用例将因无残留而失败。
        mutated_statements = [
            statement
            for statement in _split_top_level_statements(self._window_migration_sql())
            if statement.casefold() not in ("begin", "commit")
        ]
        assert mutated_statements, "mutation must keep the executable statements"
        assert all(
            statement.casefold() not in ("begin", "commit")
            for statement in mutated_statements
        )
        self._reset_window_schema()
        locker = psycopg.connect(self.server.get_uri(), autocommit=True)
        runner = psycopg.connect(self.server.get_uri(), autocommit=True)
        try:
            locker.execute("begin")
            locker.execute(
                "lock table public.planning_occurrence in access exclusive mode")
            runner.execute("set statement_timeout = '1s'")
            with self.assertRaises(psycopg.errors.QueryCanceled):
                for statement in mutated_statements:
                    runner.execute(statement)
            # 无显式事务边界：每条语句各自隐式提交——前半段残留
            assert self._window_column_count() == 2  # planning_task 两列已提交
            assert self._constraint_count(
                "public.planning_task", "planning_task_window_tod_shape_check") == 1
            assert self._constraint_count(
                "public.planning_occurrence",
                "planning_occurrence_window_at_order_check") == 0
        finally:
            runner.close()
            locker.execute("rollback")  # 释放排他锁
            locker.close()
        # 清理变异残留，逐条完整重放恢复正确迁移后的形状
        self._query(
            "alter table public.planning_task "
            "drop constraint planning_task_window_tod_shape_check")
        self._query(
            "alter table public.planning_task "
            "drop column window_start_tod, drop column window_end_tod")
        self._run_migration_statement_by_statement(
            self._window_migration_sql(), self.conn)
        assert self._window_column_count() == 4
        assert self._constraint_count(
            "public.planning_task", "planning_task_window_tod_shape_check") == 1
        assert self._constraint_count(
            "public.planning_occurrence",
            "planning_occurrence_window_at_order_check") == 1


if __name__ == "__main__":
    unittest.main()
