"""Real-migration execution test for the rumination continuity path.

Opt-in because the stack is heavyweight:

    QIGATEWAY_PG_MIGRATION_TEST=1 python -m pytest \
        tests/test_rumination_migration_pgserver_integration.py -v

The test never touches any production database. It replays the whole
migration history (including 20260905010000_rumination_continuity_path.sql)
on a throwaway PostgreSQL + pgserver instance, seeds fast-path shapes, and
exercises the rumination RPCs end to end: cursor initialization, claim lease,
atomic batch commit, thread adoption and version chains, terminal states,
request re-filing rules, and the recall exclusion of closed threads.

Every test is self-sufficient: setUp clears leftover live rumination runs and
resets the rumination cursor, so execution order never matters.
"""

import hashlib
import json
import os
import shutil
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MIGRATIONS_DIR = ROOT / "supabase" / "migrations"
PG_TRGM_LINE = "create extension if not exists pg_trgm with schema extensions;"
PG_TRGM_FILE = "20260804020000_auto_digest_memory_requests.sql"

try:
    import pgserver
    import psycopg
    _STACK_AVAILABLE = True
except ImportError:  # pragma: no cover - optional heavyweight stack
    _STACK_AVAILABLE = False


def _ensure_pg_timezone_data():
    """pgserver 的 PostgreSQL 没有附带 IANA 时区文件。"""
    pg_install = Path(pgserver.__file__).parent / "pginstall"
    tzdir = pg_install / "share" / "postgresql" / "timezone"
    if (tzdir / "Asia" / "Shanghai").exists():
        return
    try:
        import tzdata
    except ImportError:  # pragma: no cover - depends on environment
        raise unittest.SkipTest("Python tzdata package unavailable")
    src = Path(tzdata.__file__).parent / "zoneinfo"
    tzdir.mkdir(parents=True, exist_ok=True)
    shutil.copytree(src, tzdir, dirs_exist_ok=True)


def _sha256(text: str) -> str:
    return hashlib.sha256(text.casefold().encode("utf-8")).hexdigest()


ASSISTANT = "a-rumination"

EPISODE_DATA = {
    "beginning": "约好赶海", "development": "讨论装备与时间",
    "outcome": "定在下周三清晨", "closure_quality": "complete",
}

BASELINE_SQL = """
create role anon nologin;
create role authenticated nologin;
create role service_role nologin bypassrls;

create schema if not exists extensions;
create extension if not exists vector with schema extensions;

create function extensions.similarity(p_left text, p_right text)
returns double precision
language sql
immutable
parallel safe
as $stub$
    select case when p_left = p_right then 1.0 else 0.0 end
$stub$;

grant usage on schema public, extensions to anon, authenticated, service_role;

create table public.chat_messages (
    id bigint generated by default as identity primary key,
    assistant_id text not null,
    conversation_id text,
    role text,
    content text,
    created_at timestamptz not null default now()
);

create table public.memories (
    id integer generated by default as identity primary key,
    content text not null,
    title text,
    tags text[],
    heat double precision not null default 50,
    importance integer,
    layer text,
    embedding extensions.vector,
    source text,
    verified text not null default 'verified',
    is_active boolean not null default true,
    emotion_weight double precision,
    recall_count integer not null default 0,
    digest_run_id bigint,
    source_first_message_id bigint,
    source_last_message_id bigint,
    confidence double precision,
    content_hash text unique,
    created_at timestamptz not null default now(),
    last_recalled_at timestamptz
);

create table public.memory_digest_runs (
    id bigint generated by default as identity primary key,
    assistant_id text not null,
    mode text not null default 'execute',
    status text not null default 'running',
    trigger text,
    source_first_message_id bigint,
    source_last_message_id bigint,
    started_at timestamptz not null default now(),
    completed_at timestamptz,
    message_count integer,
    extracted_count integer,
    inserted_count integer,
    preview_memories jsonb,
    error_code text,
    error_message text
);

create table public.memory_digest_cursors (
    id bigint generated by default as identity primary key,
    assistant_id text not null unique,
    last_processed_message_id bigint not null default 0,
    last_success_at timestamptz,
    updated_at timestamptz not null default now()
);

grant select, update on public.memories to service_role;
"""

SEED_SQL = """
-- Chat windows: 501..520 (first batch), 521..530 (later lifecycle evidence).
insert into public.chat_messages (id, assistant_id, conversation_id, role, content, created_at) values
    (501, 'a-rumination', 'c1', 'user', '下周三天气好的话我们就去赶海。', '2026-09-01 10:00+08'),
    (502, 'a-rumination', 'c1', 'assistant', '好，我会提醒你带防晒。', '2026-09-01 10:01+08'),
    (503, 'a-rumination', 'c1', 'user', '记得提醒我涂贝壳。', '2026-09-01 10:02+08'),
    (504, 'a-rumination', 'c1', 'assistant', '贝壳已经记住了。', '2026-09-01 10:03+08'),
    (505, 'a-rumination', 'c1', 'user', '这次赶海可能要暂停，天气预报说要下雨。', '2026-09-02 09:00+08'),
    (506, 'a-rumination', 'c1', 'assistant', '那我们先观察天气。', '2026-09-02 09:01+08'),
    (507, 'a-rumination', 'c1', 'user', '天气转晴了，赶海重新安排上。', '2026-09-03 09:00+08'),
    (508, 'a-rumination', 'c1', 'assistant', '好，继续盯周三。', '2026-09-03 09:01+08'),
    (509, 'a-rumination', 'c1', 'user', '周三顺利赶海完成，收获了很多贝壳。', '2026-09-04 20:00+08'),
    (510, 'a-rumination', 'c1', 'assistant', '完美的收尾。', '2026-09-04 20:01+08'),
    (511, 'a-rumination', 'c1', 'user', '这段赶海经历真完整。', '2026-09-04 20:02+08'),
    (512, 'a-rumination', 'c1', 'assistant', '值得记住。', '2026-09-04 20:03+08'),
    (513, 'a-rumination', 'c1', 'user', '把赶海的时间定在清晨吧。', '2026-09-05 09:00+08'),
    (514, 'a-rumination', 'c1', 'assistant', '清晨赶海，记下了。', '2026-09-05 09:01+08'),
    (515, 'a-rumination', 'c1', 'user', '以后赶海话题都要提醒防晒。', '2026-09-05 09:02+08'),
    (516, 'a-rumination', 'c1', 'assistant', '明白了。', '2026-09-05 09:03+08'),
    (517, 'a-rumination', 'c1', 'user', '贝壳这个词真好用。', '2026-09-05 09:04+08'),
    (518, 'a-rumination', 'c1', 'assistant', '我们的专属代号。', '2026-09-05 09:05+08'),
    (519, 'a-rumination', 'c1', 'user', '这次经历里最难忘的是清晨的潮水。', '2026-09-05 09:06+08'),
    (520, 'a-rumination', 'c1', 'assistant', '确实难忘。', '2026-09-05 09:07+08'),
    (521, 'a-rumination', 'c1', 'user', '赶海确认成行了，天气晴。', '2026-09-06 09:00+08'),
    (522, 'a-rumination', 'c1', 'assistant', '好，那就定下来了。', '2026-09-06 09:01+08'),
    (523, 'a-rumination', 'c1', 'user', '赶海要暂停一周，我出差。', '2026-09-07 09:00+08'),
    (524, 'a-rumination', 'c1', 'assistant', '等你回来继续。', '2026-09-07 09:01+08'),
    (525, 'a-rumination', 'c1', 'user', '出差回来，赶海继续推进。', '2026-09-08 09:00+08'),
    (526, 'a-rumination', 'c1', 'assistant', '欢迎回来。', '2026-09-08 09:01+08'),
    (527, 'a-rumination', 'c1', 'user', '赶海正式完成了，潮水很美。', '2026-09-09 09:00+08'),
    (528, 'a-rumination', 'c1', 'assistant', '圆满结束。', '2026-09-09 09:01+08'),
    (529, 'a-rumination', 'c1', 'user', '新证据：这次赶海让我爱上清晨。', '2026-09-10 09:00+08'),
    (530, 'a-rumination', 'c1', 'assistant', '记下了。', '2026-09-10 09:01+08');

-- A fast-path open thread awaiting adoption (producer defaults to fast_path).
insert into public.memory_continuity_objects (continuity_id, assistant_id)
    values ('21111111-1111-1111-1111-1111111111f1', 'a-rumination');
insert into public.memories (
    content, title, tags, importance, embedding, source, verified, is_active,
    assistant_id, confidence, content_hash,
    continuity_id, continuity_schema_version, continuity_data,
    continuity_type, thread_state, evidence_message_ids,
    evidence_start_time, evidence_end_time, evidence_time_precision,
    recall_scene, recall_tags, recall_embedding
) values (
    '叶子和栖约好下周三赶海，正在确认天气。',
    '赶海行程', '{thread}', 6, '[0.1,0.2,0.3]', 'daily_digest', 'verified', true,
    'a-rumination', 0.9,
    '__FAST_THREAD_HASH__',
    '21111111-1111-1111-1111-1111111111f1', 1,
    '{"open_question": "下周三赶海是否成行", "current_state": "已约定待确认天气", "closure_criteria": ["成行或改期"]}'::jsonb,
    'thread', 'open', '{501,502}',
    '2026-09-01 10:00+08', '2026-09-01 10:01+08', 'minute',
    '确认赶海行程时', '{赶海}', '[0.2,0.2,0.2]'
);

-- An active open thread produced by an earlier rumination batch (recallable).
insert into public.memory_continuity_objects (continuity_id, assistant_id)
    values ('21111111-1111-1111-1111-1111111111f2', 'a-rumination');
insert into public.memories (
    content, title, tags, importance, embedding, source, verified, is_active,
    assistant_id, confidence, content_hash, memory_key,
    continuity_id, continuity_schema_version, continuity_data,
    continuity_type, thread_state, evidence_message_ids,
    evidence_start_time, evidence_end_time, evidence_time_precision,
    recall_scene, recall_tags, recall_embedding,
    producer_path, maintained_by
) values (
    '赶海计划当前状态：约定下周三出行，等待天气确认。',
    '赶海计划', '{thread}', 6, '[0.1,0.2,0.3]', 'rumination', 'verified', true,
    'a-rumination', 0.9,
    '__RUM_THREAD_HASH__', 'topic.haishan.plan',
    '21111111-1111-1111-1111-1111111111f2', 1,
    '{"open_question": "赶海计划是否成行", "current_state": "约定下周三出行，等待天气确认", "closure_criteria": ["成行或取消"]}'::jsonb,
    'thread', 'open', '{501,502}',
    '2026-09-01 10:00+08', '2026-09-01 10:01+08', 'minute',
    '讨论赶海计划时', '{赶海,计划}', '[0.2,0.2,0.2]',
    'rumination', 'rumination'
);

-- A second rumination thread reserved for the unchanged-update test.
insert into public.memory_continuity_objects (continuity_id, assistant_id)
    values ('21111111-1111-1111-1111-1111111111f4', 'a-rumination');
insert into public.memories (
    content, title, tags, importance, embedding, source, verified, is_active,
    assistant_id, confidence, content_hash, memory_key,
    continuity_id, continuity_schema_version, continuity_data,
    continuity_type, thread_state, evidence_message_ids,
    recall_scene, recall_tags, recall_embedding,
    producer_path, maintained_by
) values (
    '夜间观察计划当前状态：约定观察猎户座，等待晴夜。',
    '夜间观察计划', '{thread}', 5, '[0.15,0.25,0.35]', 'rumination', 'verified', true,
    'a-rumination', 0.9,
    '__RUM_THREAD2_HASH__', 'topic.night.watch',
    '21111111-1111-1111-1111-1111111111f4', 1,
    '{"open_question": "夜间观察是否成行", "current_state": "约定观察猎户座，等待晴夜", "closure_criteria": ["观察完成或取消"]}'::jsonb,
    'thread', 'open', '{501,502}',
    '讨论夜间观察时', '{夜间,观察}', '[0.15,0.15,0.15]',
    'rumination', 'rumination'
);

-- An active moment used for direct-write dedupe checks.
insert into public.memory_continuity_objects (continuity_id, assistant_id)
    values ('21111111-1111-1111-1111-1111111111f3', 'a-rumination');
insert into public.memories (
    content, title, tags, importance, embedding, source, verified, is_active,
    assistant_id, confidence, content_hash,
    continuity_id, continuity_schema_version, continuity_data,
    continuity_type, evidence_message_ids,
    producer_path, maintained_by
) values (
    '叶子和栖把防晒霜叫作贝壳的瞬间。',
    '贝壳瞬间', '{moment}', 5, '[0.3,0.1,0.2]', 'rumination', 'verified', true,
    'a-rumination', 0.9,
    '__MOMENT_HASH__',
    '21111111-1111-1111-1111-1111111111f3', 1,
    '{"scene": "聊天窗口", "event": "把防晒霜叫贝壳", "moment_state": "standalone"}'::jsonb,
    'moment', '{503}',
    'rumination', 'rumination'
);

-- Dedicated recall fixture: a resolved rumination thread that must stay out
-- of default recall while remaining visible to direct queries.
insert into public.memory_continuity_objects (continuity_id, assistant_id)
    values ('21111111-1111-1111-1111-1111111111f5', 'a-rumination');
insert into public.memories (
    content, title, tags, importance, embedding, source, verified, is_active,
    assistant_id, confidence, content_hash, memory_key,
    continuity_id, continuity_schema_version, continuity_data,
    continuity_type, thread_state, evidence_message_ids,
    evidence_start_time, evidence_end_time, evidence_time_precision,
    recall_scene, recall_tags, recall_embedding,
    producer_path, maintained_by
) values (
    '赶海回顾进程已明确完成：双方顺利赶海并整理收获。',
    '赶海回顾', '{thread}', 6, '[0.25,0.25,0.25]', 'rumination', 'verified', true,
    'a-rumination', 0.9,
    '__RESOLVED_THREAD_HASH__', 'topic.haishan.review',
    '21111111-1111-1111-1111-1111111111f5', 1,
    '{"open_question": "赶海回顾是否完成", "current_state": "回顾已写完", "closure_criteria": ["回顾完成"], "closure_summary": "双方顺利赶海并整理收获。", "closure_reason": "原文明确说明完成", "closed_at": "2026-09-09"}'::jsonb,
    'thread', 'resolved', '{509,511}',
    '2026-09-04 20:00+08', '2026-09-04 20:03+08', 'minute',
    '回顾赶海经历时', '{赶海,回顾}', '[0.25,0.25,0.25]',
    'rumination', 'rumination'
);

insert into public.memory_rumination_cursors (assistant_id) values ('a-rumination');
"""


class RuminationMigrationOnPostgresTests(unittest.TestCase):
    """Executes the rumination RPCs on a real, disposable database."""

    @classmethod
    def setUpClass(cls):
        if not _STACK_AVAILABLE:
            raise unittest.SkipTest("pgserver + psycopg are not installed")
        if os.environ.get("QIGATEWAY_PG_MIGRATION_TEST") != "1":
            raise unittest.SkipTest(
                "set QIGATEWAY_PG_MIGRATION_TEST=1 to run the real "
                "PostgreSQL migration execution test"
            )
        cls.pgdata = Path(tempfile.mkdtemp(prefix="qigate-rumination-"))
        cls.server = None
        cls.conn = None
        try:
            _ensure_pg_timezone_data()
            cls.server = pgserver.get_server(cls.pgdata, cleanup_mode="stop")
            cls.conn = psycopg.connect(cls.server.get_uri(), autocommit=True)
            cls.conn.execute(BASELINE_SQL)
            cls._apply_history()
            cls._seed()
        except Exception:
            cls.tearDownClass()
            raise

    @classmethod
    def tearDownClass(cls):
        conn = getattr(cls, "conn", None)
        if conn is not None:
            conn.close()
            cls.conn = None
        server = getattr(cls, "server", None)
        if server is not None:
            server.cleanup()
            cls.server = None
        pgdata = getattr(cls, "pgdata", None)
        if pgdata is not None and pgdata.exists():
            shutil.rmtree(pgdata, ignore_errors=True)

    # -- helpers ----------------------------------------------------------

    def _query(self, sql, params=None):
        with self.conn.cursor() as cur:
            cur.execute(sql, params)
            return cur.fetchall()

    def _query_one(self, sql, params=None):
        rows = self._query(sql, params)
        return rows[0][0] if rows else None

    def _query_row(self, sql, params=None):
        rows = self._query(sql, params)
        return tuple(rows[0]) if rows else None

    def _call(self, name, params):
        from psycopg import sql as psql

        parts = []
        values = []
        for value in params.values():
            if isinstance(value, (dict, list)):
                parts.append(psql.SQL("%s::jsonb"))
                values.append(json.dumps(value))
            elif isinstance(value, bool):
                parts.append(psql.SQL("%s::boolean"))
                values.append(value)
            elif isinstance(value, int):
                parts.append(psql.SQL("%s::bigint"))
                values.append(value)
            else:
                parts.append(psql.SQL("%s::text"))
                values.append(None if value is None else str(value))
        query = psql.SQL("select public.{name}({args})").format(
            name=psql.SQL(name),
            args=psql.SQL(", ").join(parts),
        )
        with self.conn.cursor() as cur:
            cur.execute(query, values)
            row = cur.fetchall()[0][0]
        if isinstance(row, str):
            return json.loads(row)
        return row

    @classmethod
    def _apply_history(cls):
        for path in sorted(MIGRATIONS_DIR.glob("*.sql")):
            sql = path.read_text(encoding="utf-8")
            if path.name == PG_TRGM_FILE:
                sql = sql.replace(PG_TRGM_LINE, "-- pg_trgm stubbed (pgserver)")
            cls.conn.execute(sql)

    @classmethod
    def _seed(cls):
        # Multi-statement SQL cannot go through the extended protocol with
        # parameters, so the hashes are inlined as quoted literals.
        cls.conn.execute(
            SEED_SQL
            .replace("__FAST_THREAD_HASH__", _sha256("叶子和栖约好下周三赶海，正在确认天气。"))
            .replace("__RUM_THREAD_HASH__", _sha256("赶海计划当前状态：约定下周三出行，等待天气确认。"))
            .replace("__RUM_THREAD2_HASH__", _sha256("夜间观察计划当前状态：约定观察猎户座，等待晴夜。"))
            .replace("__MOMENT_HASH__", _sha256("叶子和栖把防晒霜叫作贝壳的瞬间。"))
            .replace("__RESOLVED_THREAD_HASH__", _sha256("赶海回顾进程已明确完成：双方顺利赶海并整理收获。"))
        )

    def setUp(self):
        # Every test is order-independent: no leftover live runs and a cursor
        # at a known position.
        self.conn.execute(
            "update public.memory_digest_runs set status = 'failed', "
            "error_code = 'test_cleanup' "
            "where pipeline = 'rumination' and status in ('claimed', 'running')"
        )
        self._set_cursor(initialized=False, value=0)

    def _set_cursor(self, *, initialized: bool, value: int):
        self.conn.execute(
            "update public.memory_rumination_cursors set initialized = %s, "
            "last_processed_message_id = %s, last_scheduled_date = null "
            "where assistant_id = %s",
            (initialized, value, ASSISTANT),
        )

    def _claim(self, first, last, *, trigger="rumination_manual", first_batch=False):
        claim = self._call("claim_rumination_batch", {
            "p_assistant_id": ASSISTANT,
            "p_trigger": trigger,
            "p_first_message_id": first,
            "p_last_message_id": last,
            "p_message_count": last - first + 1,
            "p_first_batch": first_batch,
        })
        self.assertEqual(claim["status"], "claimed", claim)
        return claim["run_id"]

    def _commit(self, run_id, ops):
        return self._call("commit_rumination_batch", {
            "p_run_id": run_id,
            "p_ops": {"operations": ops},
        })

    def _cursor(self):
        return self._query_one(
            "select last_processed_message_id from public.memory_rumination_cursors "
            "where assistant_id = %s",
            (ASSISTANT,),
        )

    def _initialized(self):
        return self._query_one(
            "select initialized from public.memory_rumination_cursors "
            "where assistant_id = %s",
            (ASSISTANT,),
        )

    def _active_memory(self, where, params=None):
        return self._query_one(
            f"select id from public.memories where is_active and verified = 'verified' and {where}",
            params,
        )

    # -- cursor & claim ----------------------------------------------------

    def test_cursor_row_defaults_are_uninitialized(self):
        row = self._call("get_or_create_rumination_cursor", {"p_assistant_id": ASSISTANT})
        self.assertFalse(row["initialized"])
        self.assertEqual(row["last_processed_message_id"], 0)

    def test_first_batch_claim_records_window_and_holds_lease(self):
        run_id = self._claim(501, 520, first_batch=True)

        second = self._call("claim_rumination_batch", {
            "p_assistant_id": ASSISTANT,
            "p_trigger": "rumination_manual",
            "p_first_message_id": 521,
            "p_last_message_id": 530,
            "p_message_count": 10,
            "p_first_batch": False,
        })
        self.assertEqual(second["status"], "already_running")
        self.assertEqual(int(second["run_id"]), int(run_id))

        run = self._query_row(
            "select pipeline, status, source_first_message_id, source_last_message_id, "
            "message_count from public.memory_digest_runs where id = %s",
            (run_id,),
        )
        self.assertEqual(run[0], "rumination")
        self.assertEqual(run[1], "running")
        self.assertEqual((run[2], run[3], run[4]), (501, 520, 20))

    def test_batch_stale_rejected_after_cursor_advance(self):
        self._set_cursor(initialized=True, value=520)
        stale = self._call("claim_rumination_batch", {
            "p_assistant_id": ASSISTANT,
            "p_trigger": "rumination_manual",
            "p_first_message_id": 500,
            "p_last_message_id": 519,
            "p_message_count": 20,
            "p_first_batch": False,
        })
        self.assertEqual(stale["status"], "batch_stale")
        self.assertEqual(int(stale["cursor"]), 520)

    def test_first_batch_refused_once_initialized(self):
        self._set_cursor(initialized=True, value=520)
        result = self._call("claim_rumination_batch", {
            "p_assistant_id": ASSISTANT,
            "p_trigger": "rumination_manual",
            "p_first_message_id": 501,
            "p_last_message_id": 520,
            "p_message_count": 20,
            "p_first_batch": True,
        })
        self.assertEqual(result["status"], "already_initialized")

    def test_skipped_run_keeps_cursor_and_marks_scheduled_date(self):
        self._set_cursor(initialized=True, value=520)
        result = self._call("record_rumination_skipped", {
            "p_assistant_id": ASSISTANT,
            "p_trigger": "rumination_scheduled",
            "p_backlog_count": 45,
            "p_reason": "backlog below threshold",
        })
        self.assertEqual(result["status"], "skipped")
        run = self._query_row(
            "select status, error_code, message_count from public.memory_digest_runs "
            "where id = %s",
            (result["run_id"],),
        )
        self.assertEqual(run[0], "skipped")
        self.assertEqual(run[1], "waiting_for_batch_threshold")
        self.assertEqual(run[2], 45)
        self.assertEqual(self._cursor(), 520)
        self.assertIsNotNone(self._query_one(
            "select last_scheduled_date from public.memory_rumination_cursors "
            "where assistant_id = %s",
            (ASSISTANT,),
        ))

    # -- atomic commit ------------------------------------------------------

    def test_full_first_batch_writes_rumination_products(self):
        run_id = self._claim(501, 520, first_batch=True)
        emb = "[0.11,0.22,0.33]"
        fast_thread_id = self._active_memory(
            "content = '叶子和栖约好下周三赶海，正在确认天气。'"
        )
        result = self._commit(run_id, [
            {
                "op": "create_tracked_thread",
                "reason": "原文出现明确的长期进程",
                "content": "赶海计划新状态：双方约定下周三出行，等待天气确认。",
                "title": "赶海计划追踪",
                "thread_state": "open",
                "memory_key": "topic.trip.haishan",
                "continuity_data": {
                    "open_question": "下周三赶海是否成行",
                    "current_state": "双方约定下周三出行，等待天气确认",
                    "next_expected": "周三前确认天气",
                    "closure_criteria": ["成行或改期"],
                },
                "evidence_message_ids": [501, 502],
                "content_hash": _sha256("赶海计划新状态：双方约定下周三出行，等待天气确认。"),
                "importance": 6, "confidence": 0.9,
                "source_type": "natural_chat",
                "recall_scene": "讨论赶海计划时",
                "recall_tags": ["赶海"],
                "embedding": emb, "recall_embedding": emb,
            },
            {
                "op": "create_memory",
                "reason": "值得单独记住的瞬间",
                "continuity_type": "moment",
                "content": "赶海前夜双方一起检查装备的瞬间。",
                "title": "装备检查",
                "continuity_data": {
                    "scene": "聊天窗口", "event": "一起检查赶海装备",
                    "moment_state": "standalone",
                },
                "evidence_message_ids": [503],
                "content_hash": _sha256("赶海前夜双方一起检查装备的瞬间。"),
                "importance": 5, "confidence": 0.8,
                "embedding": emb,
            },
            {
                "op": "adopt_thread",
                "reason": "快速路径 thread 值得长期追踪",
                "target_memory_id": fast_thread_id,
                "memory_key": "topic.trip.weather",
                "evidence_message_ids": [501],
            },
            {
                "op": "create_request",
                "reason": "完整经历需要叶子审核",
                "continuity_type": "episode",
                "content": "从约定到成行的完整赶海经历。",
                "title": "赶海经历",
                "continuity_data": EPISODE_DATA,
                "evidence_message_ids": [509, 511],
                "content_hash": _sha256("从约定到成行的完整赶海经历。"),
                "importance": 6, "confidence": 0.8,
                "embedding": emb,
            },
        ])

        self.assertTrue(self._initialized())
        self.assertEqual(self._cursor(), 520)

        counts = result["op_counts"]
        self.assertEqual(counts["created_threads"], 1)
        self.assertEqual(counts["created_memories"], 1)
        self.assertEqual(counts["adopted_threads"], 1)
        self.assertEqual(counts["created_requests"], 1)

        # Direct thread write is rumination-provenance with a stable key.
        thread = self._query_row(
            "select producer_path, maintained_by, memory_key, thread_state, source "
            "from public.memories where memory_key = 'topic.trip.haishan'"
        )
        self.assertEqual(
            thread,
            ("rumination", "rumination", "topic.trip.haishan", "open", "rumination"),
        )

        # The contentless adopt is an in-place takeover: the fast-path row
        # stays active (original evidence preserved) with a stable key and
        # the rumination maintainer marker.
        adopted = self._query_row(
            "select is_active, memory_key, maintained_by, producer_path, "
            "evidence_message_ids @> '{501}'::bigint[], continuity_id "
            "from public.memories where id = %s",
            (fast_thread_id,),
        )
        self.assertEqual(
            (adopted[0], adopted[1], adopted[2], adopted[3]),
            (True, "topic.trip.weather", "rumination", "fast_path"),
        )
        self.assertTrue(adopted[4])

        # Handoff audit row exists for the adoption.
        handoff = self._query_row(
            "select kind, fast_path_memory_id, rumination_memory_id, memory_key "
            "from public.memory_path_handoffs where run_id = %s",
            (run_id,),
        )
        self.assertEqual(handoff[0], "adopt_thread")
        self.assertEqual(handoff[1], fast_thread_id)
        self.assertEqual(handoff[2], fast_thread_id)
        self.assertEqual(handoff[3], "topic.trip.weather")

        # Rumination request is pending with explicit provenance.
        request = self._query_row(
            "select status, source, producer_path, continuity_type, update_mode "
            "from public.memory_requests "
            "where digest_run_id = %s and source = 'rumination'",
            (run_id,),
        )
        self.assertEqual(request[0], "pending")
        self.assertEqual(request[1], "rumination")
        self.assertEqual(request[2], "rumination")
        self.assertEqual(request[3], "episode")
        self.assertEqual(request[4], "append")

        # The run closed as succeeded with one preview entry per op.
        run = self._query_row(
            "select status, extracted_count, inserted_count, "
            "jsonb_array_length(preview_memories) "
            "from public.memory_digest_runs where id = %s",
            (run_id,),
        )
        self.assertEqual(run[0], "succeeded")
        self.assertEqual(run[1], 4)
        self.assertEqual(run[3], 4)

    def test_versioned_adopt_takes_over_fast_path_thread(self):
        self._set_cursor(initialized=True, value=520)
        # A second fast-path thread to adopt with new content.
        self.conn.execute(
            "insert into public.memory_continuity_objects (continuity_id, assistant_id) "
            "values ('21111111-1111-1111-1111-1111111111f6', 'a-rumination')"
        )
        self.conn.execute(
            "insert into public.memories ("
            "content, title, tags, importance, embedding, source, verified, is_active, "
            "assistant_id, confidence, content_hash, "
            "continuity_id, continuity_schema_version, continuity_data, "
            "continuity_type, thread_state, evidence_message_ids "
            ") values ("
            "'旧版：双方约定周末整理相册，尚未开始。', "
            "'相册整理', '{thread}', 5, '[0.12,0.22,0.32]', 'daily_digest', 'verified', true, "
            "'a-rumination', 0.9, %s, "
            "'21111111-1111-1111-1111-1111111111f6', 1, "
            "'{\"open_question\": \"相册整理是否开始\", \"current_state\": \"约定周末整理，尚未开始\"}'::jsonb, "
            "'thread', 'open', '{504}'"
            ")",
            (_sha256("旧版：双方约定周末整理相册，尚未开始。"),),
        )
        fast_id = self._active_memory(
            "content = '旧版：双方约定周末整理相册，尚未开始。'"
        )
        run_id = self._claim(521, 522)
        new_content = "相册整理进程当前状态：周末整理已完成一半。"
        result = self._commit(run_id, [{
            "op": "adopt_thread",
            "reason": "快速路径 thread 有实质进展，值得长期追踪",
            "target_memory_id": fast_id,
            "memory_key": "topic.album.sorting",
            "content": new_content,
            "thread_state": "open",
            "continuity_data": {
                "open_question": "相册整理是否完成",
                "current_state": "周末整理已完成一半",
                "next_expected": "下次继续整理剩余部分",
                "closure_criteria": ["整理完成"],
            },
            "evidence_message_ids": [521],
            "content_hash": _sha256(new_content),
            "embedding": "[0.45,0.45,0.45]",
        }])
        self.assertEqual(result["op_counts"]["adopted_threads"], 1)

        old = self._query_row(
            "select is_active, superseded_by_memory_id is not null, maintained_by, "
            "producer_path from public.memories where id = %s",
            (fast_id,),
        )
        self.assertEqual((old[0], old[1]), (False, True))
        self.assertEqual(old[2], "fast_path")
        self.assertEqual(old[3], "fast_path")

        new = self._query_row(
            "select memory_key, supersedes_memory_id, producer_path, maintained_by, "
            "continuity_id, thread_state from public.memories "
            "where supersedes_memory_id = %s and is_active",
            (fast_id,),
        )
        self.assertEqual(new[0], "topic.album.sorting")
        self.assertEqual(new[2], "rumination")
        self.assertEqual(new[3], "rumination")
        self.assertEqual(new[5], "open")
        fast_continuity = self._query_one(
            "select continuity_id from public.memories where id = %s", (fast_id,),
        )
        self.assertEqual(new[4], fast_continuity)

        handoff = self._query_row(
            "select kind, fast_path_memory_id, rumination_memory_id "
            "from public.memory_path_handoffs where run_id = %s",
            (run_id,),
        )
        self.assertEqual(handoff[0], "adopt_thread")
        self.assertEqual(handoff[1], fast_id)
        self.assertEqual(handoff[2], self._query_one(
            "select id from public.memories where supersedes_memory_id = %s and is_active",
            (fast_id,),
        ))

    def test_hallucinated_evidence_aborts_batch_without_cursor_move(self):
        run_id = self._claim(501, 520, first_batch=True)
        with self.assertRaises(Exception):
            self._commit(run_id, [{
                "op": "create_memory",
                "reason": "引用了不存在的消息",
                "continuity_type": "moment",
                "content": "这是一条引用幻觉证据的记忆。",
                "continuity_data": {
                    "scene": "聊天窗口", "event": "幻觉", "moment_state": "standalone",
                },
                "evidence_message_ids": [99999],
                "content_hash": _sha256("这是一条引用幻觉证据的记忆。"),
                "embedding": "[0.1,0.2,0.3]",
            }])
        # Transaction rolled back: run still running, cursor untouched.
        self.assertEqual(self._query_one(
            "select status from public.memory_digest_runs where id = %s", (run_id,),
        ), "running")
        self.assertFalse(self._initialized())
        self.assertEqual(self._cursor(), 0)

    def test_out_of_window_evidence_is_rejected(self):
        self._set_cursor(initialized=True, value=520)
        run_id = self._claim(521, 530)
        rum_thread = self._active_memory("memory_key = 'topic.haishan.plan'")
        with self.assertRaises(Exception):
            self._commit(run_id, [{
                "op": "evidence_only",
                "reason": "证据不属于本批",
                "target_memory_id": rum_thread,
                "evidence_message_ids": [501],
            }])
        self.assertEqual(self._cursor(), 520)

    def test_evidence_only_then_pause_then_resume_then_resolve(self):
        self._set_cursor(initialized=True, value=520)
        rum_id = self._active_memory("memory_key = 'topic.haishan.plan'")

        run_id = self._claim(521, 524)
        result = self._commit(run_id, [
            {
                "op": "evidence_only",
                "reason": "重复表达，只补证据",
                "target_memory_id": rum_id,
                "evidence_message_ids": [521],
            },
            {
                "op": "pause_thread",
                "reason": "原文明确说明暂停一周",
                "target_memory_id": rum_id,
                "content": "赶海计划当前状态：因出差暂停一周。",
                "title": "赶海计划",
                "continuity_data": {
                    "open_question": "赶海计划是否成行",
                    "current_state": "因出差暂停一周",
                    "closure_criteria": ["成行或取消"],
                },
                "evidence_message_ids": [523],
                "content_hash": _sha256("赶海计划当前状态：因出差暂停一周。"),
                "embedding": "[0.4,0.4,0.4]",
            },
        ])
        self.assertEqual(result["op_counts"]["evidence_only"], 1)
        self.assertEqual(result["op_counts"]["paused"], 1)

        # Evidence merged into the current version; pause created a version
        # with the same key and continuity_id and a bidirectional chain.
        self.assertTrue(self._query_one(
            "select evidence_message_ids @> '{521}'::bigint[] "
            "from public.memories where id = %s", (rum_id,),
        ))
        old = self._query_row(
            "select is_active, thread_state, superseded_by_memory_id is not null "
            "from public.memories where id = %s", (rum_id,),
        )
        self.assertEqual((old[0], old[1], old[2]), (False, "open", True))
        paused_id = self._query_one(
            "select id from public.memories where supersedes_memory_id = %s and is_active",
            (rum_id,),
        )
        paused = self._query_row(
            "select thread_state, memory_key, "
            "evidence_message_ids @> '{521}'::bigint[], producer_path, maintained_by, "
            "superseded_by_memory_id is null "
            "from public.memories where id = %s", (paused_id,),
        )
        self.assertEqual(paused[0], "paused")
        self.assertEqual(paused[1], "topic.haishan.plan")
        self.assertTrue(paused[2])
        self.assertEqual((paused[3], paused[4]), ("rumination", "rumination"))
        self.assertTrue(paused[5])

        # Resume in one batch, then resolve in the next: a version op
        # deactivates the addressed version, so a thread can gain at most one
        # new version per batch and later ops must target the new id.
        run_id = self._claim(525, 526)
        result = self._commit(run_id, [
            {
                "op": "resume_thread",
                "reason": "出差回来，进程重新推进",
                "target_memory_id": paused_id,
                "content": "赶海计划当前状态：出差结束，赶海继续推进。",
                "title": "赶海计划",
                "continuity_data": {
                    "open_question": "赶海计划是否成行",
                    "current_state": "出差结束，赶海继续推进",
                    "closure_criteria": ["成行或取消"],
                },
                "evidence_message_ids": [525],
                "content_hash": _sha256("赶海计划当前状态：出差结束，赶海继续推进。"),
                "embedding": "[0.5,0.5,0.5]",
            },
        ])
        self.assertEqual(result["op_counts"]["resumed"], 1)

        resumed_id = self._query_one(
            "select id from public.memories where supersedes_memory_id = %s and is_active",
            (paused_id,),
        )
        run_id = self._claim(527, 528)
        result = self._commit(run_id, [
            {
                "op": "resolve_thread",
                "reason": "原文明确说明赶海完成",
                "target_memory_id": resumed_id,
                "content": "赶海计划已明确完成，潮水很美。",
                "title": "赶海计划",
                "continuity_data": {
                    "open_question": "赶海计划是否成行",
                    "current_state": "已明确完成",
                    "closure_criteria": ["成行或取消"],
                    "closure_summary": "双方顺利赶海，计划完成。",
                    "closure_reason": "原文明确说明完成",
                    "closed_at": "2026-09-09",
                },
                "evidence_message_ids": [527],
                "content_hash": _sha256("赶海计划已明确完成，潮水很美。"),
                "memory_time": "2026-09-09",
                "time_precision": "day",
                "embedding": "[0.6,0.6,0.6]",
            },
        ])
        self.assertEqual(result["op_counts"]["resolved"], 1)

        resolved_id = self._query_one(
            "select id from public.memories where supersedes_memory_id = %s and is_active",
            (resumed_id,),
        )
        plan_continuity = self._query_one(
            "select continuity_id from public.memories where id = %s", (rum_id,),
        )
        resolved = self._query_row(
            "select thread_state, memory_key, continuity_id, "
            "continuity_data->>'closure_summary', memory_time::date::text, "
            "time_precision from public.memories where id = %s",
            (resolved_id,),
        )
        self.assertEqual(resolved[0], "resolved")
        self.assertEqual(resolved[1], "topic.haishan.plan")
        self.assertEqual(resolved[2], plan_continuity)
        self.assertEqual(resolved[3], "双方顺利赶海，计划完成。")
        self.assertEqual(resolved[4], "2026-09-09")
        self.assertEqual(resolved[5], "day")

    def test_unchanged_update_downgrades_to_evidence_merge(self):
        self._set_cursor(initialized=True, value=520)
        watch_id = self._active_memory("memory_key = 'topic.night.watch'")
        current_content = self._query_one(
            "select content from public.memories where id = %s", (watch_id,),
        )
        run_id = self._claim(521, 522)
        result = self._commit(run_id, [{
            "op": "update_thread",
            "reason": "没有实质进展，只重复当前状态",
            "target_memory_id": watch_id,
            "content": current_content,
            "continuity_data": {
                "open_question": "夜间观察是否成行",
                "current_state": "约定观察猎户座，等待晴夜",
                "closure_criteria": ["观察完成或取消"],
            },
            "evidence_message_ids": [521],
            "content_hash": _sha256(current_content),
            "embedding": "[0.7,0.7,0.7]",
        }])
        self.assertEqual(result["op_counts"]["evidence_only"], 1)
        self.assertEqual(result["op_counts"]["updated_versions"], 0)
        self.assertEqual(self._query_one(
            "select count(*) from public.memories where supersedes_memory_id = %s",
            (watch_id,),
        ), 0)
        self.assertTrue(self._query_one(
            "select evidence_message_ids @> '{521}'::bigint[] from public.memories "
            "where id = %s", (watch_id,),
        ))

    def test_direct_write_dedupes_against_active_memory(self):
        self._set_cursor(initialized=True, value=500)
        run_id = self._claim(501, 510)
        result = self._commit(run_id, [{
            "op": "create_memory",
            "reason": "与已有正式记忆内容相同",
            "continuity_type": "moment",
            "content": "叶子和栖把防晒霜叫作贝壳的瞬间。",
            "title": "贝壳瞬间",
            "continuity_data": {
                "scene": "聊天窗口", "event": "把防晒霜叫贝壳",
                "moment_state": "standalone",
            },
            "evidence_message_ids": [503],
            "content_hash": _sha256("叶子和栖把防晒霜叫作贝壳的瞬间。"),
            "embedding": "[0.3,0.1,0.2]",
        }])
        self.assertEqual(result["op_counts"]["skipped_duplicates"], 1)
        self.assertEqual(result["op_counts"]["created_memories"], 0)

    def test_resume_requires_paused_target(self):
        self._set_cursor(initialized=True, value=520)
        watch_id = self._active_memory("memory_key = 'topic.night.watch'")
        run_id = self._claim(521, 522)
        with self.assertRaises(Exception):
            self._commit(run_id, [{
                "op": "resume_thread",
                "reason": "目标本来就是 open",
                "target_memory_id": watch_id,
                "content": "夜间观察计划当前状态：约定观察猎户座，等待晴夜。",
                "continuity_data": {
                    "open_question": "夜间观察是否成行",
                    "current_state": "约定观察猎户座，等待晴夜",
                    "closure_criteria": ["观察完成或取消"],
                },
                "evidence_message_ids": [521],
                "content_hash": _sha256("夜间观察计划当前状态：约定观察猎户座，等待晴夜。"),
                "embedding": "[0.7,0.7,0.7]",
            }])

    # -- request rules ------------------------------------------------------

    @staticmethod
    def _episode_request(content, evidence):
        return {
            "op": "create_request",
            "reason": "完整经历需要叶子审核",
            "continuity_type": "episode",
            "content": content,
            "title": "赶海经历",
            "continuity_data": EPISODE_DATA,
            "evidence_message_ids": evidence,
            "content_hash": _sha256(content),
            "importance": 6, "confidence": 0.8,
            "embedding": "[0.8,0.8,0.8]",
        }

    def _claim_and_commit(self, first, last, ops):
        self._set_cursor(initialized=True, value=first - 1)
        run_id = self._claim(first, last)
        return self._commit(run_id, ops)

    def test_identical_pending_request_blocks_second_creation(self):
        content = "一段需要审核的完整赶海episode内容。"
        result = self._claim_and_commit(521, 522, [self._episode_request(content, [521])])
        self.assertEqual(result["op_counts"]["created_requests"], 1)
        result = self._claim_and_commit(523, 524, [self._episode_request(content, [523])])
        self.assertEqual(result["op_counts"]["created_requests"], 0)
        self.assertEqual(result["op_counts"]["skipped_duplicates"], 1)

    def test_rejected_request_refiles_only_with_newer_evidence(self):
        content = "被拒后只有在出现新证据时才能重新提交的episode。"
        # First filing cites message 501 (window 501-502).
        result = self._claim_and_commit(501, 502, [self._episode_request(content, [501])])
        request_id = result["preview"][0]["request_id"]
        self.conn.execute(
            "update public.memory_requests set status = 'rejected', reviewed_at = now(), "
            "reviewed_by = 'tester' where id = %s",
            (request_id,),
        )
        # A re-file whose evidence never exceeds the prior maximum is skipped.
        result = self._claim_and_commit(501, 502, [self._episode_request(content, [501])])
        self.assertEqual(result["op_counts"]["created_requests"], 0)
        self.assertEqual(result["preview"][0]["commit_status"], "skipped_without_new_evidence")
        # A re-file citing strictly newer evidence (523 > 501) is accepted.
        result = self._claim_and_commit(523, 524, [self._episode_request(content, [523])])
        self.assertEqual(result["op_counts"]["created_requests"], 1)

    def test_interaction_rule_request_requires_key(self):
        ops = [{
            "op": "create_request",
            "reason": "叶子明确要求赶海话题提醒防晒",
            "continuity_type": "interaction_rule",
            "content": "赶海话题必须提醒防晒。",
            "continuity_data": {
                "trigger": "提到赶海", "expected_behavior": "提醒防晒",
                "scope": "全局", "priority": 5, "rule_state": "active",
                "explicit_instruction": "以后赶海话题都要提醒防晒",
            },
            "evidence_message_ids": [515],
            "content_hash": _sha256("赶海话题必须提醒防晒。"),
            "embedding": "[0.9,0.9,0.9]",
        }]
        with self.assertRaises(Exception):
            self._claim_and_commit(515, 516, ops)

    def test_interaction_rule_request_with_key_is_created(self):
        ops = [{
            "op": "create_request",
            "reason": "叶子明确要求赶海话题提醒防晒",
            "continuity_type": "interaction_rule",
            "content": "赶海话题必须提醒防晒，这是明确指令。",
            "continuity_data": {
                "trigger": "提到赶海", "expected_behavior": "提醒防晒",
                "scope": "全局", "priority": 5, "rule_state": "active",
                "explicit_instruction": "以后赶海话题都要提醒防晒",
            },
            "memory_key": "rule.haishan.sunscreen",
            "evidence_message_ids": [515],
            "content_hash": _sha256("赶海话题必须提醒防晒，这是明确指令。"),
            "embedding": "[0.9,0.9,0.9]",
        }]
        result = self._claim_and_commit(515, 516, ops)
        self.assertEqual(result["op_counts"]["created_requests"], 1)
        row = self._query_row(
            "select memory_key, update_mode, continuity_type, producer_path "
            "from public.memory_requests where source = 'rumination' "
            "and continuity_type = 'interaction_rule' limit 1"
        )
        self.assertEqual(row[0], "rule.haishan.sunscreen")
        self.assertEqual(row[1], "replace")
        self.assertEqual(row[3], "rumination")

    # -- fast-path gating ---------------------------------------------------

    def _thread_candidate_item(self, content, content_hash, thread_state="open"):
        return {
            "continuity_type": "thread",
            "thread_state": thread_state,
            "continuity_schema_version": 1,
            "continuity_data": {
                "open_question": " gate 候选的开放问题",
                "current_state": " gate 候选的当前状态",
            },
            "content": content,
            "content_hash": content_hash,
            "embedding": "[0.2,0.2,0.2]",
            "evidence_message_ids": [501],
            "evidence_start_time": "2026-09-01T10:00:00+08:00",
            "evidence_end_time": "2026-09-01T10:01:00+08:00",
            "evidence_time_precision": "minute",
            "recall_scene": "确认赶海行程时",
            "recall_embedding": "[0.2,0.2,0.2]",
            "importance": 5,
            "confidence": 0.8,
            "update_mode": "append",
        }

    def _staged_continuity_run(self):
        self.conn.execute(
            "insert into public.memory_digest_runs (assistant_id, pipeline, trigger, "
            "mode, status, source_first_message_id, source_last_message_id, message_count) "
            "values ('a-rumination', 'continuity', 'continuity_manual', 'execute', 'running', "
            "501, 520, 20) returning id"
        )
        return self._query_one(
            "select id from public.memory_digest_runs where pipeline = 'continuity' "
            "order by id desc limit 1"
        )

    def _store_candidate(self, run_id, item):
        """Call store_continuity_candidate with the run row and a jsonb item."""
        return self._query_one(
            "select public.store_continuity_candidate(run, %s::jsonb) "
            "from public.memory_digest_runs as run where run.id = %s",
            (json.dumps(item), run_id),
        )

    def _seed_gate_thread(self, content, key):
        """Create a dedicated active rumination thread for gate tests so the
        assertions never depend on other tests' lifecycle mutations."""
        self.conn.execute(
            "insert into public.memory_continuity_objects (continuity_id, assistant_id) "
            "values ('21111111-1111-1111-1111-1111111111f7', 'a-rumination') "
            "on conflict (continuity_id) do nothing"
        )
        self.conn.execute(
            "insert into public.memories ("
            "content, title, tags, importance, embedding, source, verified, is_active, "
            "assistant_id, confidence, content_hash, memory_key, "
            "continuity_id, continuity_schema_version, continuity_data, "
            "continuity_type, thread_state, evidence_message_ids, "
            "producer_path, maintained_by "
            ") values ("
            "%s, '门控夹具', '{thread}', 5, '[0.2,0.2,0.2]', 'rumination', 'verified', true, "
            "'a-rumination', 0.9, %s, %s, "
            "'21111111-1111-1111-1111-1111111111f7', 1, "
            "'{\"open_question\": \"门控夹具是否推进\", \"current_state\": \"门控夹具当前状态\"}'::jsonb, "
            "'thread', 'open', '{501}', "
            "'rumination', 'rumination'"
            ") on conflict (content_hash) do nothing",
            (content, _sha256(content), key),
        )
        return self._query_one(
            "select id from public.memories where memory_key = %s and is_active", (key,)
        )

    def test_fast_path_thread_matching_rumination_thread_stays_pending(self):
        gate_id = self._seed_gate_thread(
            "门控夹具线程当前状态：双方约定周末整理相册。",
            "topic.gate.fixture",
        )
        rum_content = self._query_one(
            "select content from public.memories where id = %s", (gate_id,)
        )
        run_id = self._staged_continuity_run()
        # The candidate content exactly equals the rumination thread's body
        # (the stub similarity only scores exact matches), while the caller
        # supplied content hash differs, mirroring similar-but-not-identical
        # content reaching the similarity gate.
        inserted = self._store_candidate(run_id, self._thread_candidate_item(
            rum_content, "f" * 64,
        ))
        self.assertEqual(inserted, 1)
        request = self._query_row(
            "select status, continuity_type from public.memory_requests "
            "where content_hash = %s",
            ("f" * 64,),
        )
        self.assertIsNotNone(request)
        # Gated: the candidate stays pending instead of auto-approving into a
        # parallel active truth next to the rumination thread.
        self.assertEqual(request[0], "pending")
        self.assertIsNone(self._query_one(
            "select id from public.memories where content_hash = %s", ("f" * 64,),
        ))

    def test_fast_path_thread_without_rumination_match_auto_approves(self):
        self._seed_gate_thread(
            "门控夹具线程当前状态：双方约定周末整理相册。",
            "topic.gate.fixture",
        )
        run_id = self._staged_continuity_run()
        content = "一个与反刍长期进程完全无关的独立线索候选。"
        inserted = self._store_candidate(run_id, self._thread_candidate_item(
            content, _sha256(content),
        ))
        self.assertEqual(inserted, 1)
        # Not gated: the candidate auto-approved into a formal thread.
        self.assertIsNotNone(self._query_one(
            "select id from public.memories where content_hash = %s and is_active",
            (_sha256(content),),
        ))

    def test_direct_thread_write_conflicts_with_rumination_thread(self):
        gate_id = self._seed_gate_thread(
            "门控夹具线程当前状态：双方约定周末整理相册。",
            "topic.gate.fixture",
        )
        gate_content = self._query_one(
            "select content from public.memories where id = %s", (gate_id,),
        )
        with self.assertRaises(Exception) as raised:
            self._query_one(
                "select public.write_memory_direct_v1(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)",
                (
                    ASSISTANT, "c1", 501, gate_content, "赶海计划", "{thread}" , 5,
                    "与反刍 thread 相同的正文", "a" * 64, "direct-conflict-key", 6,
                    None, "append", "thread", "open", 1,
                    json.dumps({"open_question": "x", "current_state": "y"}),
                    "natural_chat", "mcp_memory", "orangechat_ai",
                    "讨论赶海计划时", "{赶海}", None,
                ),
            )
        self.assertIn("memory_thread_rumination_conflict", str(raised.exception))

    def test_direct_replace_on_rumination_maintained_key_is_refused(self):
        self._seed_gate_thread(
            "门控夹具线程当前状态：双方约定周末整理相册。",
            "topic.gate.fixture",
        )
        with self.assertRaises(Exception) as raised:
            self._query_one(
                "select public.write_memory_direct_v1(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)",
                (
                    ASSISTANT, "c1", 501, "快速路径想改写反刍维护的当前状态。",
                    "赶海计划", "{thread}", 5, "replace 改写", "b" * 64,
                    "direct-maintained-key", 6, "topic.gate.fixture", "replace",
                    "thread", "open", 1,
                    json.dumps({"open_question": "x", "current_state": "y"}),
                    "natural_chat", "mcp_memory", "orangechat_ai",
                    "讨论赶海计划时", "{赶海}", None,
                ),
            )
        self.assertIn("memory_thread_rumination_maintained", str(raised.exception))

    # -- recall embedding atomicity -----------------------------------------

    def test_missing_recall_embedding_aborts_batch_atomically(self):
        self._set_cursor(initialized=True, value=500)
        objects_before = self._query_one(
            "select count(*) from public.memory_continuity_objects"
        )
        memories_before = self._query_one("select count(*) from public.memories")
        run_id = self._claim(501, 510)
        with self.assertRaises(Exception) as raised:
            self._commit(run_id, [{
                "op": "create_memory",
                "reason": "有场景但缺召回向量",
                "continuity_type": "moment",
                "content": "一条带召回场景却缺向量的记忆。",
                "continuity_data": {
                    "scene": "聊天窗口", "event": "缺向量", "moment_state": "standalone",
                },
                "recall_scene": "聊到缺向量写入时",
                "evidence_message_ids": [503],
                "content_hash": _sha256("一条带召回场景却缺向量的记忆。"),
                "embedding": "[0.2,0.2,0.2]",
            }])
        self.assertIn("memory_rumination_missing_recall_embedding", str(raised.exception))
        # 整批回滚：无记忆行、无 continuity 对象、游标不动、run 未提交。
        self.assertEqual(
            self._query_one("select count(*) from public.memories"), memories_before,
        )
        self.assertEqual(
            self._query_one("select count(*) from public.memory_continuity_objects"),
            objects_before,
        )
        self.assertEqual(self._cursor(), 500)
        self.assertEqual(self._query_one(
            "select status from public.memory_digest_runs where id = %s", (run_id,),
        ), "running")

    def test_missing_recall_embedding_retry_after_fix_succeeds(self):
        self._set_cursor(initialized=True, value=500)
        content = "一条带召回场景却缺向量的记忆。"
        ops_without_vector = [{
            "op": "create_memory",
            "reason": "有场景但缺召回向量",
            "continuity_type": "moment",
            "content": content,
            "continuity_data": {
                "scene": "聊天窗口", "event": "缺向量", "moment_state": "standalone",
            },
            "recall_scene": "聊到缺向量写入时",
            "evidence_message_ids": [503],
            "content_hash": _sha256(content),
            "embedding": "[0.2,0.2,0.2]",
        }]
        run_id = self._claim(501, 510)
        with self.assertRaises(Exception):
            self._commit(run_id, ops_without_vector)
        # 重试同一批：补充召回向量后成功提交，游标推进。
        ops_with_vector = [dict(ops_without_vector[0], recall_embedding="[0.2,0.2,0.2]")]
        result = self._commit(run_id, ops_with_vector)
        self.assertEqual(result["op_counts"]["created_memories"], 1)
        self.assertEqual(self._cursor(), 510)
        memory = self._query_row(
            "select recall_scene is not null, recall_embedding is not null "
            "from public.memories where content_hash = %s",
            (_sha256(content),),
        )
        self.assertEqual(memory, (True, True))

    def test_sceneless_write_keeps_null_scene_and_null_vector(self):
        self._set_cursor(initialized=True, value=500)
        content = "一条没有可靠召回场景的记忆正文。"
        run_id = self._claim(501, 510)
        result = self._commit(run_id, [{
            "op": "create_memory",
            "reason": "没有可靠场景",
            "continuity_type": "moment",
            "content": content,
            "continuity_data": {
                "scene": "聊天窗口", "event": "无场景", "moment_state": "standalone",
            },
            "evidence_message_ids": [503],
            "content_hash": _sha256(content),
            "embedding": "[0.2,0.2,0.2]",
        }])
        self.assertEqual(result["op_counts"]["created_memories"], 1)
        row = self._query_row(
            "select recall_scene is null, recall_embedding is null "
            "from public.memories where content_hash = %s",
            (_sha256(content),),
        )
        self.assertEqual(row, (True, True))

    # -- same-batch version boundary -----------------------------------------

    def test_second_version_op_on_same_target_is_rejected(self):
        # 合并由 Python 管线完成；DB 层保持防御：同批对同一 target 的第二个
        # 版本操作（旧 id 已在本事务内失活）必须失败且不推进游标。
        self._set_cursor(initialized=True, value=520)
        watch_id = self._active_memory("memory_key = 'topic.night.watch'")
        run_id = self._claim(521, 522)
        with self.assertRaises(Exception):
            self._commit(run_id, [
                {
                    "op": "update_thread",
                    "reason": "第一个进展",
                    "target_memory_id": watch_id,
                    "content": "夜间观察计划当前状态：第一次推进。",
                    "continuity_data": {
                        "open_question": "夜间观察是否成行",
                        "current_state": "第一次推进",
                        "closure_criteria": ["观察完成或取消"],
                    },
                    "evidence_message_ids": [521],
                    "content_hash": _sha256("夜间观察计划当前状态：第一次推进。"),
                    "embedding": "[0.7,0.7,0.7]",
                },
                {
                    "op": "update_thread",
                    "reason": "第二个进展",
                    "target_memory_id": watch_id,
                    "content": "夜间观察计划当前状态：第二次推进。",
                    "continuity_data": {
                        "open_question": "夜间观察是否成行",
                        "current_state": "第二次推进",
                        "closure_criteria": ["观察完成或取消"],
                    },
                    "evidence_message_ids": [522],
                    "content_hash": _sha256("夜间观察计划当前状态：第二次推进。"),
                    "embedding": "[0.75,0.75,0.75]",
                },
            ])
        self.assertEqual(self._cursor(), 520)
        self.assertEqual(self._query_one(
            "select count(*) from public.memories where supersedes_memory_id = %s",
            (watch_id,),
        ), 0)

    # -- request re-filing ----------------------------------------------------

    def test_same_batch_duplicate_request_ops_are_idempotent(self):
        self._set_cursor(initialized=True, value=520)
        content = "同批内重复提交的episode申请内容。"
        run_id = self._claim(521, 522)
        result = self._commit(run_id, [
            self._episode_request(content, [521]),
            self._episode_request(content, [521]),
        ])
        self.assertEqual(result["op_counts"]["created_requests"], 1)
        self.assertEqual(result["op_counts"]["skipped_duplicates"], 1)
        self.assertEqual(self._query_one(
            "select count(*) from public.memory_requests where content_hash = %s",
            (_sha256(content),),
        ), 1)

    def test_approved_request_blocks_refile_without_crash(self):
        content = "已通过申请的正文不得再次提交为申请。"
        self._set_cursor(initialized=True, value=520)
        run_id = self._claim(521, 522)
        result = self._commit(run_id, [self._episode_request(content, [521])])
        request_id = result["preview"][0]["request_id"]
        self.conn.execute(
            "update public.memory_requests set status = 'approved', reviewed_at = now(), "
            "reviewed_by = 'tester' where id = %s",
            (request_id,),
        )
        # approved 后重提：跳过而不是触发部分唯一索引冲突。
        self._set_cursor(initialized=True, value=520)
        run_id = self._claim(521, 522)
        result = self._commit(run_id, [self._episode_request(content, [521])])
        self.assertEqual(result["op_counts"]["created_requests"], 0)
        self.assertEqual(result["preview"][0]["commit_status"], "skipped_existing_request")

    def test_active_memory_blocks_duplicate_request(self):
        # 内容已经是正式记忆（含正式 moment 正文）时不再创建申请。
        moment_hash = self._query_one(
            "select content_hash from public.memories where is_active "
            "and content = '叶子和栖把防晒霜叫作贝壳的瞬间。'"
        )
        self._set_cursor(initialized=True, value=520)
        run_id = self._claim(521, 522)
        result = self._commit(run_id, [{
            "op": "create_request",
            "reason": "与正式记忆正文相同",
            "continuity_type": "episode",
            "content": "叶子和栖把防晒霜叫作贝壳的瞬间。",
            "continuity_data": EPISODE_DATA,
            "evidence_message_ids": [521],
            "content_hash": moment_hash,
            "importance": 6, "confidence": 0.8,
            "embedding": "[0.8,0.8,0.8]",
        }])
        self.assertEqual(result["op_counts"]["created_requests"], 0)
        self.assertEqual(result["preview"][0]["commit_status"], "skipped_active_memory")

    # -- handoff --------------------------------------------------------------

    def test_pending_request_keeps_fast_path_memory_active(self):
        self._set_cursor(initialized=True, value=500)
        fast_moment = self._active_memory(
            "content = '叶子和栖把防晒霜叫作贝壳的瞬间。'"
        )
        content = "反刍申请 pending 期间快速路径记忆必须保留的episode。"
        run_id = self._claim(501, 510)
        self._commit(run_id, [self._episode_request(content, [503])])
        self.assertIsNotNone(self._active_memory(
            "content = '叶子和栖把防晒霜叫作贝壳的瞬间。'"
        ))
        self.assertEqual(self._query_one(
            "select status from public.memory_requests where content_hash = %s",
            (_sha256(content),),
        ), "pending")

    def test_approved_rumination_request_carries_provenance(self):
        # 申请通过后，正式记忆通过既有 sync 触发器继承反刍 provenance；
        # pending 阶段没有任何快速路径记忆被移动或归档。
        content = "approved 后正式记忆应继承反刍来源的episode。"
        self._set_cursor(initialized=True, value=520)
        run_id = self._claim(521, 522)
        result = self._commit(run_id, [self._episode_request(content, [521])])
        request_id = result["preview"][0]["request_id"]
        fast_moment = self._active_memory(
            "content = '叶子和栖把防晒霜叫作贝壳的瞬间。'"
        )
        self.assertIsNotNone(fast_moment)
        # 通过现有审核 RPC 批准（叶子审核路径，不做任何改动）。
        self._query_one(
            "select public.review_memory_request_v5(%s, 'approve', %s, %s, %s, %s, %s, "
            "'tester', null, null, null, null, null, null, null, null, null)",
            (
                request_id, content, "赶海经历", "{episode}", 6, _sha256(content),
            ),
        )
        approved_memory = self._query_row(
            "select producer_path, maintained_by, source from public.memories "
            "where content_hash = %s and is_active",
            (_sha256(content),),
        )
        self.assertEqual(
            approved_memory, ("rumination", "rumination", "rumination"),
        )
        # 既有快速路径记忆不受影响。
        self.assertIsNotNone(self._active_memory(
            "content = '叶子和栖把防晒霜叫作贝壳的瞬间。'"
        ))

    def test_rejected_request_keeps_fast_path_memory_and_thread_state(self):
        self._set_cursor(initialized=True, value=500)
        fast_moment = self._active_memory(
            "content = '叶子和栖把防晒霜叫作贝壳的瞬间。'"
        )
        resolved_before = self._active_memory("memory_key = 'topic.haishan.review'")
        content = "被拒后不得影响正式记忆与已完成 thread 的episode。"
        run_id = self._claim(501, 510)
        result = self._commit(run_id, [self._episode_request(content, [503])])
        request_id = result["preview"][0]["request_id"]
        self.conn.execute(
            "update public.memory_requests set status = 'rejected', reviewed_at = now(), "
            "reviewed_by = 'tester' where id = %s",
            (request_id,),
        )
        self.assertIsNotNone(self._active_memory(
            "content = '叶子和栖把防晒霜叫作贝壳的瞬间。'"
        ))
        self.assertEqual(
            self._query_one(
                "select thread_state from public.memories where id = %s",
                (resolved_before,),
            ),
            "resolved",
        )

    def test_same_evidence_different_semantics_stay_active(self):
        # 仅证据重合不能证明语义相同：同批两条不同分类记忆互不归档。
        self._set_cursor(initialized=True, value=500)
        run_id = self._claim(501, 510)
        result = self._commit(run_id, [
            {
                "op": "create_memory",
                "reason": "值得记住的瞬间",
                "continuity_type": "moment",
                "content": "赶海清晨潮水带来的难忘瞬间。",
                "continuity_data": {
                    "scene": "海边", "event": "清晨潮水", "moment_state": "standalone",
                },
                "evidence_message_ids": [509],
                "content_hash": _sha256("赶海清晨潮水带来的难忘瞬间。"),
                "embedding": "[0.31,0.31,0.31]",
            },
            {
                "op": "create_tracked_thread",
                "reason": "新的长期进程",
                "content": "赶海记录计划当前状态：约定整理赶海收获清单。",
                "title": "赶海记录计划",
                "thread_state": "open",
                "memory_key": "topic.haishan.log",
                "continuity_data": {
                    "open_question": "收获清单是否整理完成",
                    "current_state": "约定整理赶海收获清单",
                    "closure_criteria": ["清单完成"],
                },
                "evidence_message_ids": [509, 510],
                "content_hash": _sha256("赶海记录计划当前状态：约定整理赶海收获清单。"),
                "embedding": "[0.32,0.32,0.32]",
            },
        ])
        self.assertEqual(result["op_counts"]["created_memories"], 1)
        self.assertEqual(result["op_counts"]["created_threads"], 1)
        self.assertEqual(self._query_one(
            "select count(*) from public.memories where is_active and evidence_message_ids @> '{509}'::bigint[]",
        ), 3)  # seed plan thread + new moment + new thread

    def test_handoff_batch_failure_rolls_back_everything(self):
        self._set_cursor(initialized=True, value=520)
        # A fresh fast-path thread for this test: the adopt must roll back.
        self.conn.execute(
            "insert into public.memory_continuity_objects (continuity_id, assistant_id) "
            "values ('21111111-1111-1111-1111-1111111111f8', 'a-rumination') "
            "on conflict (continuity_id) do nothing"
        )
        rollback_content = "回滚夹具：双方约定一起修补帐篷，尚未开始。"
        self.conn.execute(
            "insert into public.memories ("
            "content, title, tags, importance, embedding, source, verified, is_active, "
            "assistant_id, confidence, content_hash, memory_key, "
            "continuity_id, continuity_schema_version, continuity_data, "
            "continuity_type, thread_state, evidence_message_ids "
            ") values ("
            "%s, '帐篷修补', '{thread}', 5, '[0.18,0.28,0.38]', 'daily_digest', 'verified', true, "
            "'a-rumination', 0.9, %s, 'topic.tent.repair', "
            "'21111111-1111-1111-1111-1111111111f8', 1, "
            "'{\"open_question\": \"帐篷修补是否开始\", \"current_state\": \"约定修补，尚未开始\"}'::jsonb, "
            "'thread', 'open', '{504}'"
            ") on conflict (content_hash) do nothing",
            (rollback_content, _sha256(rollback_content)),
        )
        fast_id = self._active_memory("memory_key = 'topic.tent.repair'")
        objects_before = self._query_one(
            "select count(*) from public.memory_continuity_objects"
        )
        handoffs_before = self._query_one(
            "select count(*) from public.memory_path_handoffs"
        )
        run_id = self._claim(521, 522)
        with self.assertRaises(Exception):
            self._commit(run_id, [
                {
                    "op": "adopt_thread",
                    "reason": "先合法接管",
                    "target_memory_id": fast_id,
                    "memory_key": "topic.tent.repair",
                    "evidence_message_ids": [521],
                },
                {
                    "op": "create_memory",
                    "reason": "随后非法结构",
                    "continuity_type": "moment",
                    "content": "一条结构非法的记忆正文。",
                    "continuity_data": {
                        "scene": "s", "event": "e", "moment_state": "bogus",
                    },
                    "evidence_message_ids": [522],
                    "content_hash": _sha256("一条结构非法的记忆正文。"),
                    "embedding": "[0.4,0.4,0.4]",
                },
            ])
        # 接管与写入全部回滚：maintained_by 未翻转、无交接记录、无 continuity
        # 对象、游标不动。
        self.assertEqual(self._query_row(
            "select maintained_by, memory_key from public.memories where id = %s",
            (fast_id,),
        ), ("fast_path", "topic.tent.repair"))
        self.assertEqual(self._query_one(
            "select count(*) from public.memory_path_handoffs"
        ), handoffs_before)
        self.assertEqual(self._query_one(
            "select count(*) from public.memory_continuity_objects"
        ), objects_before)
        self.assertEqual(self._cursor(), 520)

    # -- recall -------------------------------------------------------------

    def test_resolved_thread_exits_default_recall_but_stays_queryable(self):
        resolved_id = self._active_memory("memory_key = 'topic.haishan.review'")
        self.assertIsNotNone(resolved_id)

        rows = self._query(
            "select id from public.search_memories_by_keywords(%s, %s)",
            (["赶海"], 50),
        )
        self.assertNotIn(resolved_id, [row[0] for row in rows])

        rows = self._query(
            "select id from public.match_memories('[0.25,0.25,0.25]'::extensions.vector, 0.0, 50)"
        )
        self.assertNotIn(resolved_id, [row[0] for row in rows])

        # History remains fully visible to direct admin queries.
        self.assertEqual(self._query_one(
            "select count(*) from public.memories where id = %s", (resolved_id,),
        ), 1)

    def test_open_thread_with_vector_still_recalled(self):
        open_id = self._active_memory(
            "thread_state = 'open' and recall_embedding is not null "
            "and memory_key = 'topic.night.watch'"
        )
        self.assertIsNotNone(open_id)
        rows = self._query(
            "select id from public.match_memories('[0.15,0.15,0.15]'::extensions.vector, 0.0, 50)"
        )
        self.assertIn(open_id, [row[0] for row in rows])

        rows = self._query(
            "select id from public.search_memories_by_keywords(%s, %s)",
            (["猎户座"], 50),
        )
        self.assertIn(open_id, [row[0] for row in rows])


if __name__ == "__main__":
    unittest.main()
