-- User-reviewed resolution for similar or conflicting memory applications.
-- No similarity score can mutate a durable memory automatically. Every merge,
-- duplicate link, and conflict flag is explicit, atomic, and append-only audited.
-- chat_messages remains an immutable read-only source and is not modified.

alter table public.memory_requests
    add column if not exists related_memory_id integer;

alter table public.memory_requests
    drop constraint if exists memory_requests_status_values,
    drop constraint if exists memory_requests_related_memory_fkey;

alter table public.memory_requests
    add constraint memory_requests_status_values
        check (status in (
            'pending', 'approved', 'rejected', 'merged', 'duplicate', 'conflict'
        )),
    add constraint memory_requests_related_memory_fkey
        foreign key (related_memory_id)
        references public.memories(id)
        on delete set null;

create index if not exists memory_requests_related_memory_idx
    on public.memory_requests (related_memory_id)
    where related_memory_id is not null;

comment on column public.memory_requests.related_memory_id is
    'Existing verified memory selected by the user for duplicate, conflict, or merge review.';

create table if not exists public.memory_request_review_events (
    id bigint generated by default as identity primary key,
    request_id bigint not null
        references public.memory_requests(id)
        on delete restrict,
    action text not null,
    from_status text not null,
    to_status text not null,
    target_memory_id integer
        references public.memories(id)
        on delete set null,
    result_memory_id integer
        references public.memories(id)
        on delete set null,
    reviewed_by text not null,
    review_note text,
    review_snapshot jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint memory_request_review_events_action_values
        check (action in ('approve', 'reject', 'merge', 'duplicate', 'conflict')),
    constraint memory_request_review_events_status_lengths
        check (char_length(from_status) between 1 and 24
            and char_length(to_status) between 1 and 24),
    constraint memory_request_review_events_reviewer_length
        check (char_length(reviewed_by) between 1 and 120),
    constraint memory_request_review_events_note_length
        check (review_note is null or char_length(review_note) <= 500)
);

create index if not exists memory_request_review_events_request_idx
    on public.memory_request_review_events (request_id, created_at desc);

create index if not exists memory_request_review_events_target_idx
    on public.memory_request_review_events (target_memory_id)
    where target_memory_id is not null;

create index if not exists memory_request_review_events_result_idx
    on public.memory_request_review_events (result_memory_id)
    where result_memory_id is not null;

comment on table public.memory_request_review_events is
    'Append-only audit events for user decisions on AI memory applications.';

alter table public.memory_request_review_events enable row level security;
revoke all on table public.memory_request_review_events from anon, authenticated;
revoke all on sequence public.memory_request_review_events_id_seq from anon, authenticated;
grant select, insert on table public.memory_request_review_events to service_role;
grant usage, select on sequence public.memory_request_review_events_id_seq to service_role;

create or replace function public.review_memory_request_v3(
    p_request_id bigint,
    p_action text,
    p_content text default null,
    p_title text default null,
    p_tags text[] default null,
    p_importance integer default null,
    p_content_hash text default null,
    p_reviewed_by text default 'gateway_admin',
    p_review_note text default null,
    p_memory_key text default null,
    p_update_mode text default null,
    p_related_memory_id integer default null
)
returns jsonb
language plpgsql
set search_path to 'public'
as $function$
declare
    v_request public.memory_requests%rowtype;
    v_target public.memories%rowtype;
    v_result jsonb;
    v_result_memory_id integer;
    v_from_status text;
    v_action text := lower(trim(coalesce(p_action, '')));
    v_content text;
    v_title text;
    v_tags text[];
    v_importance integer;
    v_content_hash text;
    v_target_memory_key text;
    v_reviewed_by text := left(
        coalesce(nullif(trim(p_reviewed_by), ''), 'gateway_admin'),
        120
    );
    v_review_note text := nullif(left(trim(coalesce(p_review_note, '')), 500), '');
begin
    if v_action not in ('approve', 'reject', 'merge', 'duplicate', 'conflict') then
        raise exception 'memory_request_invalid_action';
    end if;

    select * into v_request
    from public.memory_requests
    where id = p_request_id
    for update;

    if not found then
        raise exception 'memory_request_not_found';
    end if;

    v_from_status := v_request.status;

    -- Approval and rejection retain the proven v2 behavior. A conflict is an
    -- unresolved review state, so the user may later resolve it either way.
    if v_action in ('approve', 'reject') then
        if (v_action = 'approve' and v_request.status in ('approved', 'merged'))
           or (v_action = 'reject' and v_request.status = 'rejected') then
            return jsonb_build_object(
                'changed', false,
                'related_memory_id', v_request.related_memory_id,
                'request', jsonb_build_object(
                    'id', v_request.id,
                    'status', v_request.status,
                    'memory_id', v_request.memory_id,
                    'reviewed_at', v_request.reviewed_at
                )
            );
        end if;

        if v_request.status not in ('pending', 'conflict') then
            raise exception 'memory_request_not_pending';
        end if;

        if v_request.status = 'conflict' then
            update public.memory_requests
            set status = 'pending', updated_at = now()
            where id = v_request.id;
        end if;

        v_result := public.review_memory_request_v2(
            p_request_id,
            v_action,
            p_content,
            p_title,
            p_tags,
            p_importance,
            p_content_hash,
            v_reviewed_by,
            v_review_note,
            p_memory_key,
            p_update_mode
        );

        if coalesce((v_result->>'changed')::boolean, false) then
            insert into public.memory_request_review_events (
                request_id,
                action,
                from_status,
                to_status,
                target_memory_id,
                result_memory_id,
                reviewed_by,
                review_note,
                review_snapshot
            ) values (
                v_request.id,
                v_action,
                v_from_status,
                v_result->'request'->>'status',
                v_request.related_memory_id,
                nullif(v_result->'request'->>'memory_id', '')::integer,
                v_reviewed_by,
                v_review_note,
                jsonb_strip_nulls(jsonb_build_object(
                    'content', p_content,
                    'title', p_title,
                    'tags', p_tags,
                    'importance', p_importance,
                    'memory_key', p_memory_key,
                    'update_mode', p_update_mode
                ))
            );
        end if;

        return v_result || jsonb_build_object(
            'related_memory_id', v_request.related_memory_id
        );
    end if;

    if v_request.status not in ('pending', 'conflict') then
        raise exception 'memory_request_not_pending';
    end if;

    if p_related_memory_id is null then
        raise exception 'memory_request_related_memory_required';
    end if;

    -- Use the same memory-key lock order as mutable-fact replacement before
    -- taking the target lock, avoiding cross-flow races and deadlocks.
    select memory_key into v_target_memory_key
    from public.memories
    where id = p_related_memory_id;

    if not found then
        raise exception 'memory_request_related_memory_not_found';
    end if;

    if v_target_memory_key is not null then
        perform pg_advisory_xact_lock(
            hashtextextended('memory-key:' || v_target_memory_key, 0)
        );
    end if;

    -- Serialize every relational decision around the selected durable memory.
    perform pg_advisory_xact_lock(
        hashtextextended('memory-review-target:' || p_related_memory_id::text, 0)
    );

    select * into v_target
    from public.memories
    where id = p_related_memory_id
    for update;

    if not found then
        raise exception 'memory_request_related_memory_not_found';
    end if;
    if v_target.verified <> 'verified' or v_target.is_active is not true then
        raise exception 'memory_request_related_memory_inactive';
    end if;

    if v_action in ('duplicate', 'conflict') then
        if p_content is not null
           or p_title is not null
           or p_tags is not null
           or p_importance is not null
           or p_content_hash is not null
           or p_memory_key is not null
           or p_update_mode is not null then
            raise exception 'memory_request_relation_disallows_edits';
        end if;

        if v_action = 'conflict'
           and v_request.status = 'conflict'
           and v_request.related_memory_id = v_target.id then
            return jsonb_build_object(
                'changed', false,
                'related_memory_id', v_target.id,
                'request', jsonb_build_object(
                    'id', v_request.id,
                    'status', v_request.status,
                    'memory_id', v_request.memory_id,
                    'reviewed_at', v_request.reviewed_at
                )
            );
        end if;

        update public.memory_requests
        set
            status = v_action,
            memory_id = case when v_action = 'duplicate' then v_target.id else null end,
            related_memory_id = v_target.id,
            reviewed_at = now(),
            reviewed_by = v_reviewed_by,
            review_note = v_review_note,
            updated_at = now()
        where id = v_request.id
        returning * into v_request;

        insert into public.memory_request_review_events (
            request_id,
            action,
            from_status,
            to_status,
            target_memory_id,
            result_memory_id,
            reviewed_by,
            review_note,
            review_snapshot
        ) values (
            v_request.id,
            v_action,
            v_from_status,
            v_request.status,
            v_target.id,
            case when v_action = 'duplicate' then v_target.id else null end,
            v_reviewed_by,
            v_review_note,
            jsonb_build_object(
                'request_content_hash', v_request.content_hash,
                'target_content_hash', v_target.content_hash
            )
        );

        return jsonb_build_object(
            'changed', true,
            'related_memory_id', v_target.id,
            'request', jsonb_build_object(
                'id', v_request.id,
                'status', v_request.status,
                'memory_id', v_request.memory_id,
                'reviewed_at', v_request.reviewed_at
            )
        );
    end if;

    -- A merge is never inferred. The user supplies the final merged wording,
    -- while the selected target is soft-deactivated and linked to the result.
    v_content := trim(coalesce(p_content, ''));
    v_title := nullif(left(trim(coalesce(p_title, '')), 100), '');
    v_tags := coalesce(p_tags, '{}'::text[]);
    v_importance := coalesce(p_importance, 5);
    v_content_hash := trim(coalesce(p_content_hash, ''));

    if char_length(v_content) not between 5 and 600 then
        raise exception 'memory_request_invalid_content';
    end if;
    if cardinality(v_tags) > 5 then
        raise exception 'memory_request_invalid_tags';
    end if;
    if v_importance not between 1 and 10 then
        raise exception 'memory_request_invalid_importance';
    end if;
    if char_length(v_content_hash) <> 64 then
        raise exception 'memory_request_invalid_hash';
    end if;
    if p_memory_key is not null or p_update_mode is not null then
        raise exception 'memory_request_merge_disallows_update_mode';
    end if;
    if v_content_hash = v_target.content_hash then
        raise exception 'memory_request_merge_unchanged';
    end if;
    if exists (
        select 1 from public.memories
        where content_hash = v_content_hash
          and id <> v_target.id
    ) then
        raise exception 'memory_request_merge_content_exists';
    end if;

    update public.memories
    set
        is_active = false,
        superseded_at = now(),
        superseded_by_memory_id = null
    where id = v_target.id;

    insert into public.memories (
        content,
        title,
        tags,
        heat,
        importance,
        layer,
        embedding,
        source,
        verified,
        is_active,
        emotion_weight,
        recall_count,
        assistant_id,
        digest_run_id,
        source_first_message_id,
        source_last_message_id,
        confidence,
        content_hash,
        memory_key,
        supersedes_memory_id,
        superseded_by_memory_id,
        superseded_at
    ) values (
        v_content,
        v_title,
        v_tags,
        greatest(coalesce(v_target.heat, 0), least(greatest(v_importance * 10.0, 0), 100)),
        v_importance,
        case
            when v_target.layer = '核心' then '核心'
            when v_importance >= 8 then '场景'
            else '碎片'
        end,
        null,
        'ai_tool_request',
        'verified',
        true,
        coalesce(v_target.emotion_weight, 0.5),
        coalesce(v_target.recall_count, 0),
        coalesce(v_target.assistant_id, v_request.assistant_id),
        null,
        case
            when v_target.source_first_message_id is null then v_request.source_message_id
            when v_request.source_message_id is null then v_target.source_first_message_id
            else least(v_target.source_first_message_id, v_request.source_message_id)
        end,
        case
            when v_target.source_last_message_id is null then v_request.source_message_id
            when v_request.source_message_id is null then v_target.source_last_message_id
            else greatest(v_target.source_last_message_id, v_request.source_message_id)
        end,
        greatest(coalesce(v_target.confidence, 0), 1.0),
        v_content_hash,
        v_target.memory_key,
        v_target.id,
        null,
        null
    )
    returning id into v_result_memory_id;

    update public.memories
    set superseded_by_memory_id = v_result_memory_id
    where id = v_target.id;

    update public.memory_requests
    set
        content = v_content,
        title = v_title,
        tags = v_tags,
        importance = v_importance,
        content_hash = v_content_hash,
        status = 'merged',
        memory_id = v_result_memory_id,
        related_memory_id = v_target.id,
        reviewed_at = now(),
        reviewed_by = v_reviewed_by,
        review_note = v_review_note,
        updated_at = now()
    where id = v_request.id
    returning * into v_request;

    insert into public.memory_request_review_events (
        request_id,
        action,
        from_status,
        to_status,
        target_memory_id,
        result_memory_id,
        reviewed_by,
        review_note,
        review_snapshot
    ) values (
        v_request.id,
        'merge',
        v_from_status,
        v_request.status,
        v_target.id,
        v_result_memory_id,
        v_reviewed_by,
        v_review_note,
        jsonb_build_object(
            'content', v_content,
            'title', v_title,
            'tags', v_tags,
            'importance', v_importance,
            'content_hash', v_content_hash
        )
    );

    return jsonb_build_object(
        'changed', true,
        'related_memory_id', v_target.id,
        'request', jsonb_build_object(
            'id', v_request.id,
            'status', v_request.status,
            'memory_id', v_request.memory_id,
            'reviewed_at', v_request.reviewed_at
        )
    );
end;
$function$;

revoke all on function public.review_memory_request_v3(
    bigint, text, text, text, text[], integer, text, text, text, text, text, integer
) from public, anon, authenticated;

grant execute on function public.review_memory_request_v3(
    bigint, text, text, text, text[], integer, text, text, text, text, text, integer
) to service_role;

