-- Pending applications submitted by the OrangeChat request_memory tool.
-- The plugin calls qi-gateway over HTTP and never receives a Supabase server key.
-- chat_messages remains a read-only source and is intentionally not altered.

create table if not exists public.memory_requests (
    id bigint generated by default as identity primary key,
    assistant_id text not null,
    conversation_id text,
    source_message_id bigint,
    content text not null,
    title text,
    tags text[] not null default '{}'::text[],
    importance integer not null default 5,
    reason text not null,
    content_hash text not null,
    idempotency_key text not null unique,
    status text not null default 'pending',
    source text not null default 'orangechat_plugin',
    memory_id integer references public.memories(id) on delete set null,
    reviewed_at timestamptz,
    reviewed_by text,
    review_note text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint memory_requests_content_length
        check (char_length(content) between 5 and 600),
    constraint memory_requests_title_length
        check (title is null or char_length(title) <= 100),
    constraint memory_requests_reason_length
        check (char_length(reason) between 3 and 500),
    constraint memory_requests_importance_range
        check (importance between 1 and 10),
    constraint memory_requests_tags_limit
        check (cardinality(tags) <= 5),
    constraint memory_requests_status_values
        check (status in ('pending', 'approved', 'rejected', 'merged'))
);

create unique index if not exists memory_requests_active_content_idx
    on public.memory_requests (assistant_id, content_hash)
    where status in ('pending', 'approved', 'merged');

create index if not exists memory_requests_review_queue_idx
    on public.memory_requests (status, created_at desc);

create index if not exists memory_requests_assistant_idx
    on public.memory_requests (assistant_id, created_at desc);

comment on table public.memory_requests is
    'User-reviewed applications submitted by the OrangeChat request_memory tool.';

alter table public.memory_requests enable row level security;

-- Browser/client roles do not access this table directly. The gateway uses an
-- elevated server key and exposes only purpose-built authenticated endpoints.
revoke all on table public.memory_requests from anon, authenticated;
revoke all on sequence public.memory_requests_id_seq from anon, authenticated;
grant select, insert, update on table public.memory_requests to service_role;
grant usage, select on sequence public.memory_requests_id_seq to service_role;

create or replace function public.create_memory_request(
    p_assistant_id text,
    p_conversation_id text,
    p_source_message_id bigint,
    p_content text,
    p_title text,
    p_tags text[],
    p_importance integer,
    p_reason text,
    p_content_hash text,
    p_idempotency_key text,
    p_rate_limit integer default 6
)
returns jsonb
language plpgsql
set search_path to 'public'
as $function$
declare
    v_request public.memory_requests%rowtype;
    v_recent_count integer := 0;
begin
    if char_length(trim(coalesce(p_assistant_id, ''))) < 1
       or char_length(p_assistant_id) > 160 then
        raise exception 'memory_request_invalid_assistant';
    end if;
    if char_length(trim(coalesce(p_content, ''))) not between 5 and 600 then
        raise exception 'memory_request_invalid_content';
    end if;
    if char_length(trim(coalesce(p_reason, ''))) not between 3 and 500 then
        raise exception 'memory_request_invalid_reason';
    end if;
    if p_importance not between 1 and 10 then
        raise exception 'memory_request_invalid_importance';
    end if;
    if char_length(trim(coalesce(p_content_hash, ''))) <> 64 then
        raise exception 'memory_request_invalid_hash';
    end if;
    if char_length(trim(coalesce(p_idempotency_key, ''))) not between 8 and 128 then
        raise exception 'memory_request_invalid_idempotency_key';
    end if;

    -- Serialize requests per assistant so rate limiting and deduplication work
    -- across multiple gateway instances.
    perform pg_advisory_xact_lock(hashtextextended(p_assistant_id, 0));

    select * into v_request
    from public.memory_requests
    where idempotency_key = p_idempotency_key
       or (
            assistant_id = p_assistant_id
            and content_hash = p_content_hash
            and status in ('pending', 'approved', 'merged')
       )
    order by (idempotency_key = p_idempotency_key) desc, id desc
    limit 1;

    if found then
        return jsonb_build_object(
            'created', false,
            'request', jsonb_build_object(
                'id', v_request.id,
                'status', v_request.status,
                'created_at', v_request.created_at
            )
        );
    end if;

    select count(*) into v_recent_count
    from public.memory_requests
    where assistant_id = p_assistant_id
      and source = 'orangechat_plugin'
      and created_at >= now() - interval '1 minute';

    if v_recent_count >= least(greatest(coalesce(p_rate_limit, 6), 1), 60) then
        raise exception using
            errcode = 'P0001',
            message = 'memory_request_rate_limited';
    end if;

    insert into public.memory_requests (
        assistant_id,
        conversation_id,
        source_message_id,
        content,
        title,
        tags,
        importance,
        reason,
        content_hash,
        idempotency_key,
        status,
        source
    ) values (
        p_assistant_id,
        nullif(trim(p_conversation_id), ''),
        p_source_message_id,
        trim(p_content),
        nullif(trim(p_title), ''),
        coalesce(p_tags, '{}'::text[]),
        p_importance,
        trim(p_reason),
        p_content_hash,
        p_idempotency_key,
        'pending',
        'orangechat_plugin'
    )
    returning * into v_request;

    return jsonb_build_object(
        'created', true,
        'request', jsonb_build_object(
            'id', v_request.id,
            'status', v_request.status,
            'created_at', v_request.created_at
        )
    );
end;
$function$;

revoke all on function public.create_memory_request(
    text, text, bigint, text, text, text[], integer, text, text, text, integer
) from public, anon, authenticated;

grant execute on function public.create_memory_request(
    text, text, bigint, text, text, text[], integer, text, text, text, integer
) to service_role;
